// Code generated by github.com/atombender/go-jsonschema, DO NOT EDIT.

package main

import "encoding/json"
import "fmt"
import "reflect"
import "regexp"
import "unicode/utf8"

type Basis string

const BasisCompanyIncome Basis = "companyIncome"
const BasisCompanyProfit Basis = "companyProfit"
const BasisGrossDividend Basis = "grossDividend"
const BasisGrossSalary Basis = "grossSalary"

var enumValues_Basis = []interface{}{
	"companyIncome",
	"companyProfit",
	"grossSalary",
	"grossDividend",
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *Basis) UnmarshalJSON(value []byte) error {
	var v string
	if err := json.Unmarshal(value, &v); err != nil {
		return err
	}
	var ok bool
	for _, expected := range enumValues_Basis {
		if reflect.DeepEqual(v, expected) {
			ok = true
			break
		}
	}
	if !ok {
		return fmt.Errorf("invalid value (expected one of %#v): %#v", enumValues_Basis, v)
	}
	*j = Basis(v)
	return nil
}

type CompanyIncomeExpenseRow interface{}

type CompanyIncomeOrSalaryBasis string

const CompanyIncomeOrSalaryBasisCompanyIncome CompanyIncomeOrSalaryBasis = "companyIncome"
const CompanyIncomeOrSalaryBasisGrossSalary CompanyIncomeOrSalaryBasis = "grossSalary"

var enumValues_CompanyIncomeOrSalaryBasis = []interface{}{
	"companyIncome",
	"grossSalary",
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *CompanyIncomeOrSalaryBasis) UnmarshalJSON(value []byte) error {
	var v string
	if err := json.Unmarshal(value, &v); err != nil {
		return err
	}
	var ok bool
	for _, expected := range enumValues_CompanyIncomeOrSalaryBasis {
		if reflect.DeepEqual(v, expected) {
			ok = true
			break
		}
	}
	if !ok {
		return fmt.Errorf("invalid value (expected one of %#v): %#v", enumValues_CompanyIncomeOrSalaryBasis, v)
	}
	*j = CompanyIncomeOrSalaryBasis(v)
	return nil
}

type CompanyIncomeOrSalaryPercentAboveCapCalculation struct {
	// Basis corresponds to the JSON schema field "basis".
	Basis CompanyIncomeOrSalaryBasis `json:"basis" yaml:"basis" mapstructure:"basis"`

	// CapAmount corresponds to the JSON schema field "capAmount".
	CapAmount NonNegativeMoneyAmount `json:"capAmount" yaml:"capAmount" mapstructure:"capAmount"`

	// Percent corresponds to the JSON schema field "percent".
	Percent Percentage `json:"percent" yaml:"percent" mapstructure:"percent"`

	// Type corresponds to the JSON schema field "type".
	Type interface{} `json:"type" yaml:"type" mapstructure:"type"`
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *CompanyIncomeOrSalaryPercentAboveCapCalculation) UnmarshalJSON(value []byte) error {
	var raw map[string]interface{}
	if err := json.Unmarshal(value, &raw); err != nil {
		return err
	}
	if _, ok := raw["basis"]; raw != nil && !ok {
		return fmt.Errorf("field basis in CompanyIncomeOrSalaryPercentAboveCapCalculation: required")
	}
	if _, ok := raw["capAmount"]; raw != nil && !ok {
		return fmt.Errorf("field capAmount in CompanyIncomeOrSalaryPercentAboveCapCalculation: required")
	}
	if _, ok := raw["percent"]; raw != nil && !ok {
		return fmt.Errorf("field percent in CompanyIncomeOrSalaryPercentAboveCapCalculation: required")
	}
	if _, ok := raw["type"]; raw != nil && !ok {
		return fmt.Errorf("field type in CompanyIncomeOrSalaryPercentAboveCapCalculation: required")
	}
	type Plain CompanyIncomeOrSalaryPercentAboveCapCalculation
	var plain Plain
	if err := json.Unmarshal(value, &plain); err != nil {
		return err
	}
	*j = CompanyIncomeOrSalaryPercentAboveCapCalculation(plain)
	return nil
}

type CompanyIncomeOrSalaryPercentBelowCapCalculation struct {
	// Basis corresponds to the JSON schema field "basis".
	Basis CompanyIncomeOrSalaryBasis `json:"basis" yaml:"basis" mapstructure:"basis"`

	// CapAmount corresponds to the JSON schema field "capAmount".
	CapAmount NonNegativeMoneyAmount `json:"capAmount" yaml:"capAmount" mapstructure:"capAmount"`

	// Percent corresponds to the JSON schema field "percent".
	Percent Percentage `json:"percent" yaml:"percent" mapstructure:"percent"`

	// Type corresponds to the JSON schema field "type".
	Type interface{} `json:"type" yaml:"type" mapstructure:"type"`
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *CompanyIncomeOrSalaryPercentBelowCapCalculation) UnmarshalJSON(value []byte) error {
	var raw map[string]interface{}
	if err := json.Unmarshal(value, &raw); err != nil {
		return err
	}
	if _, ok := raw["basis"]; raw != nil && !ok {
		return fmt.Errorf("field basis in CompanyIncomeOrSalaryPercentBelowCapCalculation: required")
	}
	if _, ok := raw["capAmount"]; raw != nil && !ok {
		return fmt.Errorf("field capAmount in CompanyIncomeOrSalaryPercentBelowCapCalculation: required")
	}
	if _, ok := raw["percent"]; raw != nil && !ok {
		return fmt.Errorf("field percent in CompanyIncomeOrSalaryPercentBelowCapCalculation: required")
	}
	if _, ok := raw["type"]; raw != nil && !ok {
		return fmt.Errorf("field type in CompanyIncomeOrSalaryPercentBelowCapCalculation: required")
	}
	type Plain CompanyIncomeOrSalaryPercentBelowCapCalculation
	var plain Plain
	if err := json.Unmarshal(value, &plain); err != nil {
		return err
	}
	*j = CompanyIncomeOrSalaryPercentBelowCapCalculation(plain)
	return nil
}

type CompanyIncomeOrSalaryPercentCalculation struct {
	// Basis corresponds to the JSON schema field "basis".
	Basis CompanyIncomeOrSalaryBasis `json:"basis" yaml:"basis" mapstructure:"basis"`

	// Percent corresponds to the JSON schema field "percent".
	Percent Percentage `json:"percent" yaml:"percent" mapstructure:"percent"`

	// Type corresponds to the JSON schema field "type".
	Type interface{} `json:"type" yaml:"type" mapstructure:"type"`
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *CompanyIncomeOrSalaryPercentCalculation) UnmarshalJSON(value []byte) error {
	var raw map[string]interface{}
	if err := json.Unmarshal(value, &raw); err != nil {
		return err
	}
	if _, ok := raw["basis"]; raw != nil && !ok {
		return fmt.Errorf("field basis in CompanyIncomeOrSalaryPercentCalculation: required")
	}
	if _, ok := raw["percent"]; raw != nil && !ok {
		return fmt.Errorf("field percent in CompanyIncomeOrSalaryPercentCalculation: required")
	}
	if _, ok := raw["type"]; raw != nil && !ok {
		return fmt.Errorf("field type in CompanyIncomeOrSalaryPercentCalculation: required")
	}
	type Plain CompanyIncomeOrSalaryPercentCalculation
	var plain Plain
	if err := json.Unmarshal(value, &plain); err != nil {
		return err
	}
	*j = CompanyIncomeOrSalaryPercentCalculation(plain)
	return nil
}

type CompanyProfitExpenseRow interface{}

type CompanyProfitPercentAboveCapCalculation struct {
	// Basis corresponds to the JSON schema field "basis".
	Basis interface{} `json:"basis" yaml:"basis" mapstructure:"basis"`

	// CapAmount corresponds to the JSON schema field "capAmount".
	CapAmount NonNegativeMoneyAmount `json:"capAmount" yaml:"capAmount" mapstructure:"capAmount"`

	// Percent corresponds to the JSON schema field "percent".
	Percent Percentage `json:"percent" yaml:"percent" mapstructure:"percent"`

	// Type corresponds to the JSON schema field "type".
	Type interface{} `json:"type" yaml:"type" mapstructure:"type"`
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *CompanyProfitPercentAboveCapCalculation) UnmarshalJSON(value []byte) error {
	var raw map[string]interface{}
	if err := json.Unmarshal(value, &raw); err != nil {
		return err
	}
	if _, ok := raw["basis"]; raw != nil && !ok {
		return fmt.Errorf("field basis in CompanyProfitPercentAboveCapCalculation: required")
	}
	if _, ok := raw["capAmount"]; raw != nil && !ok {
		return fmt.Errorf("field capAmount in CompanyProfitPercentAboveCapCalculation: required")
	}
	if _, ok := raw["percent"]; raw != nil && !ok {
		return fmt.Errorf("field percent in CompanyProfitPercentAboveCapCalculation: required")
	}
	if _, ok := raw["type"]; raw != nil && !ok {
		return fmt.Errorf("field type in CompanyProfitPercentAboveCapCalculation: required")
	}
	type Plain CompanyProfitPercentAboveCapCalculation
	var plain Plain
	if err := json.Unmarshal(value, &plain); err != nil {
		return err
	}
	*j = CompanyProfitPercentAboveCapCalculation(plain)
	return nil
}

type CompanyProfitPercentBelowCapCalculation struct {
	// Basis corresponds to the JSON schema field "basis".
	Basis interface{} `json:"basis" yaml:"basis" mapstructure:"basis"`

	// CapAmount corresponds to the JSON schema field "capAmount".
	CapAmount NonNegativeMoneyAmount `json:"capAmount" yaml:"capAmount" mapstructure:"capAmount"`

	// Percent corresponds to the JSON schema field "percent".
	Percent Percentage `json:"percent" yaml:"percent" mapstructure:"percent"`

	// Type corresponds to the JSON schema field "type".
	Type interface{} `json:"type" yaml:"type" mapstructure:"type"`
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *CompanyProfitPercentBelowCapCalculation) UnmarshalJSON(value []byte) error {
	var raw map[string]interface{}
	if err := json.Unmarshal(value, &raw); err != nil {
		return err
	}
	if _, ok := raw["basis"]; raw != nil && !ok {
		return fmt.Errorf("field basis in CompanyProfitPercentBelowCapCalculation: required")
	}
	if _, ok := raw["capAmount"]; raw != nil && !ok {
		return fmt.Errorf("field capAmount in CompanyProfitPercentBelowCapCalculation: required")
	}
	if _, ok := raw["percent"]; raw != nil && !ok {
		return fmt.Errorf("field percent in CompanyProfitPercentBelowCapCalculation: required")
	}
	if _, ok := raw["type"]; raw != nil && !ok {
		return fmt.Errorf("field type in CompanyProfitPercentBelowCapCalculation: required")
	}
	type Plain CompanyProfitPercentBelowCapCalculation
	var plain Plain
	if err := json.Unmarshal(value, &plain); err != nil {
		return err
	}
	*j = CompanyProfitPercentBelowCapCalculation(plain)
	return nil
}

type CompanyProfitPercentCalculation struct {
	// Basis corresponds to the JSON schema field "basis".
	Basis interface{} `json:"basis" yaml:"basis" mapstructure:"basis"`

	// Percent corresponds to the JSON schema field "percent".
	Percent Percentage `json:"percent" yaml:"percent" mapstructure:"percent"`

	// Type corresponds to the JSON schema field "type".
	Type interface{} `json:"type" yaml:"type" mapstructure:"type"`
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *CompanyProfitPercentCalculation) UnmarshalJSON(value []byte) error {
	var raw map[string]interface{}
	if err := json.Unmarshal(value, &raw); err != nil {
		return err
	}
	if _, ok := raw["basis"]; raw != nil && !ok {
		return fmt.Errorf("field basis in CompanyProfitPercentCalculation: required")
	}
	if _, ok := raw["percent"]; raw != nil && !ok {
		return fmt.Errorf("field percent in CompanyProfitPercentCalculation: required")
	}
	if _, ok := raw["type"]; raw != nil && !ok {
		return fmt.Errorf("field type in CompanyProfitPercentCalculation: required")
	}
	type Plain CompanyProfitPercentCalculation
	var plain Plain
	if err := json.Unmarshal(value, &plain); err != nil {
		return err
	}
	*j = CompanyProfitPercentCalculation(plain)
	return nil
}

// Configuration schema for the expense and salary/dividend model used by Income
// Atlas. Each configuration includes UI metadata plus spreadsheet-like calculation
// rules. Company income is calculated elsewhere, then configurable rows are
// applied in four ordered groups. The configuration describes assumptions; it does
// not configure the search algorithm. The application optimizer always maximizes
// totalUsableIncome = netSalary + netDividend. Both grossSalary and grossDividend
// may be fixed, zero, residual, percent-based, or optimized. companyProfit and
// companyTotal are implicit non-negative invariants: if no explicit minimum is
// configured, their minimum is 0.
type ExpensesSchemaJson struct {
	// Optional schema reference in configuration documents.
	Schema *string `json:"$schema,omitempty,omitzero" yaml:"$schema,omitempty" mapstructure:"$schema,omitempty"`

	// Optional hard constraints. Omitted constraints are disabled.
	Constraints *ExpensesSchemaJsonConstraints `json:"constraints,omitempty,omitzero" yaml:"constraints,omitempty" mapstructure:"constraints,omitempty"`

	// Main currency for fixed amounts. Use ISO 4217 such as EUR, BGN, RON, CHF.
	Currency string `json:"currency" yaml:"currency" mapstructure:"currency"`

	// Human-readable explanatory text shown below the title. May contain trusted HTML
	// if the application chooses to render it as HTML; schema validation only treats
	// it as a string.
	Description string `json:"description" yaml:"description" mapstructure:"description"`

	// The four ordered groups used by the model. Rows are freely named; each row
	// declares a calculation type and basis.
	ExpenseGroups ExpensesSchemaJsonExpenseGroups `json:"expenseGroups" yaml:"expenseGroups" mapstructure:"expenseGroups"`

	// Short UI label for selecting this configuration, for example a tab label or
	// dropdown label. Keep this concise.
	Label string `json:"label" yaml:"label" mapstructure:"label"`

	// Defines how gross salary and gross dividend are determined. The objective is
	// not configurable: the application maximizes totalUsableIncome = netSalary +
	// netDividend whenever one or both gross amounts are optimized. If neither gross
	// amount is optimized, the configuration is just evaluated as a calculation. The
	// search strategy, candidate generation, cap probing, refinement, and caching are
	// application concerns, not schema fields.
	Optimization ExpensesSchemaJsonOptimization `json:"optimization" yaml:"optimization" mapstructure:"optimization"`

	// Human-readable title shown as the main heading for this configuration.
	Title string `json:"title" yaml:"title" mapstructure:"title"`
}

// Optional hard constraints. Omitted constraints are disabled.
type ExpensesSchemaJsonConstraints struct {
	// Optional maximum gross dividend as percent of gross salary. Omitted means
	// disabled. Example: 10 means gross dividend may not exceed 10% of gross salary.
	MaximumDividendToSalaryPercent *Percentage `json:"maximumDividendToSalaryPercent,omitempty,omitzero" yaml:"maximumDividendToSalaryPercent,omitempty" mapstructure:"maximumDividendToSalaryPercent,omitempty"`

	// Optional lower bound for gross salary. Useful for immigration, legal, or
	// practical minimum salary assumptions.
	MinimumGrossSalary MinimumRule `json:"minimumGrossSalary,omitempty,omitzero" yaml:"minimumGrossSalary,omitempty" mapstructure:"minimumGrossSalary,omitempty"`
}

// The four ordered groups used by the model. Rows are freely named; each row
// declares a calculation type and basis.
type ExpensesSchemaJsonExpenseGroups struct {
	// Pre-profit company-side rows. Subtracted from company income before company
	// profit is calculated. Typical rows: fixed business costs, percentage of income,
	// gross-salary-related employer costs.
	CompanyIncomeExpenses []CompanyIncomeExpenseRow `json:"companyIncomeExpenses" yaml:"companyIncomeExpenses" mapstructure:"companyIncomeExpenses"`

	// Profit-level company rows. Subtracted from company profit. Typical rows:
	// corporate income tax, forced reserve based on profit.
	CompanyProfitExpenses []CompanyProfitExpenseRow `json:"companyProfitExpenses" yaml:"companyProfitExpenses" mapstructure:"companyProfitExpenses"`

	// Personal deductions from gross dividend. These reduce gross dividend to net
	// dividend. Typical rows: dividend withholding tax and dividend-related
	// health/social charges.
	GrossDividendExpenses []GrossDividendExpenseRow `json:"grossDividendExpenses" yaml:"grossDividendExpenses" mapstructure:"grossDividendExpenses"`

	// Personal deductions from gross salary. These reduce gross salary to net salary.
	// Typical rows: employee social contributions, employee health insurance, salary
	// income tax.
	GrossSalaryExpenses []GrossSalaryExpenseRow `json:"grossSalaryExpenses" yaml:"grossSalaryExpenses" mapstructure:"grossSalaryExpenses"`
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *ExpensesSchemaJsonExpenseGroups) UnmarshalJSON(value []byte) error {
	var raw map[string]interface{}
	if err := json.Unmarshal(value, &raw); err != nil {
		return err
	}
	if _, ok := raw["companyIncomeExpenses"]; raw != nil && !ok {
		return fmt.Errorf("field companyIncomeExpenses in ExpensesSchemaJsonExpenseGroups: required")
	}
	if _, ok := raw["companyProfitExpenses"]; raw != nil && !ok {
		return fmt.Errorf("field companyProfitExpenses in ExpensesSchemaJsonExpenseGroups: required")
	}
	if _, ok := raw["grossDividendExpenses"]; raw != nil && !ok {
		return fmt.Errorf("field grossDividendExpenses in ExpensesSchemaJsonExpenseGroups: required")
	}
	if _, ok := raw["grossSalaryExpenses"]; raw != nil && !ok {
		return fmt.Errorf("field grossSalaryExpenses in ExpensesSchemaJsonExpenseGroups: required")
	}
	type Plain ExpensesSchemaJsonExpenseGroups
	var plain Plain
	if err := json.Unmarshal(value, &plain); err != nil {
		return err
	}
	if v, ok := raw["companyIncomeExpenses"]; !ok || v == nil {
		plain.CompanyIncomeExpenses = []CompanyIncomeExpenseRow{}
	}
	if v, ok := raw["companyProfitExpenses"]; !ok || v == nil {
		plain.CompanyProfitExpenses = []CompanyProfitExpenseRow{}
	}
	if v, ok := raw["grossDividendExpenses"]; !ok || v == nil {
		plain.GrossDividendExpenses = []GrossDividendExpenseRow{}
	}
	if v, ok := raw["grossSalaryExpenses"]; !ok || v == nil {
		plain.GrossSalaryExpenses = []GrossSalaryExpenseRow{}
	}
	*j = ExpensesSchemaJsonExpenseGroups(plain)
	return nil
}

// Defines how gross salary and gross dividend are determined. The objective is not
// configurable: the application maximizes totalUsableIncome = netSalary +
// netDividend whenever one or both gross amounts are optimized. If neither gross
// amount is optimized, the configuration is just evaluated as a calculation. The
// search strategy, candidate generation, cap probing, refinement, and caching are
// application concerns, not schema fields.
type ExpensesSchemaJsonOptimization struct {
	// GrossDividend corresponds to the JSON schema field "grossDividend".
	GrossDividend GrossDividendRule `json:"grossDividend" yaml:"grossDividend" mapstructure:"grossDividend"`

	// GrossSalary corresponds to the JSON schema field "grossSalary".
	GrossSalary GrossSalaryRule `json:"grossSalary" yaml:"grossSalary" mapstructure:"grossSalary"`

	// Optional minimum result constraints. Omitted minimums are disabled, except
	// companyProfit and companyTotal: these are special model invariants with an
	// implicit minimum of 0. These are lower bounds, not optimization targets.
	Minimums *ExpensesSchemaJsonOptimizationMinimums `json:"minimums,omitempty,omitzero" yaml:"minimums,omitempty" mapstructure:"minimums,omitempty"`
}

// Optional minimum result constraints. Omitted minimums are disabled, except
// companyProfit and companyTotal: these are special model invariants with an
// implicit minimum of 0. These are lower bounds, not optimization targets.
type ExpensesSchemaJsonOptimizationMinimums struct {
	// CompanyProfit corresponds to the JSON schema field "companyProfit".
	CompanyProfit MinimumRule `json:"companyProfit,omitempty,omitzero" yaml:"companyProfit,omitempty" mapstructure:"companyProfit,omitempty"`

	// CompanyTotal corresponds to the JSON schema field "companyTotal".
	CompanyTotal MinimumRule `json:"companyTotal,omitempty,omitzero" yaml:"companyTotal,omitempty" mapstructure:"companyTotal,omitempty"`

	// GrossDividend corresponds to the JSON schema field "grossDividend".
	GrossDividend MinimumRule `json:"grossDividend,omitempty,omitzero" yaml:"grossDividend,omitempty" mapstructure:"grossDividend,omitempty"`

	// GrossSalary corresponds to the JSON schema field "grossSalary".
	GrossSalary MinimumRule `json:"grossSalary,omitempty,omitzero" yaml:"grossSalary,omitempty" mapstructure:"grossSalary,omitempty"`

	// TotalUsableIncome corresponds to the JSON schema field "totalUsableIncome".
	TotalUsableIncome MinimumRule `json:"totalUsableIncome,omitempty,omitzero" yaml:"totalUsableIncome,omitempty" mapstructure:"totalUsableIncome,omitempty"`
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *ExpensesSchemaJsonOptimization) UnmarshalJSON(value []byte) error {
	var raw map[string]interface{}
	if err := json.Unmarshal(value, &raw); err != nil {
		return err
	}
	if _, ok := raw["grossDividend"]; raw != nil && !ok {
		return fmt.Errorf("field grossDividend in ExpensesSchemaJsonOptimization: required")
	}
	if _, ok := raw["grossSalary"]; raw != nil && !ok {
		return fmt.Errorf("field grossSalary in ExpensesSchemaJsonOptimization: required")
	}
	type Plain ExpensesSchemaJsonOptimization
	var plain Plain
	if err := json.Unmarshal(value, &plain); err != nil {
		return err
	}
	*j = ExpensesSchemaJsonOptimization(plain)
	return nil
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *ExpensesSchemaJson) UnmarshalJSON(value []byte) error {
	var raw map[string]interface{}
	if err := json.Unmarshal(value, &raw); err != nil {
		return err
	}
	if _, ok := raw["currency"]; raw != nil && !ok {
		return fmt.Errorf("field currency in ExpensesSchemaJson: required")
	}
	if _, ok := raw["description"]; raw != nil && !ok {
		return fmt.Errorf("field description in ExpensesSchemaJson: required")
	}
	if _, ok := raw["expenseGroups"]; raw != nil && !ok {
		return fmt.Errorf("field expenseGroups in ExpensesSchemaJson: required")
	}
	if _, ok := raw["label"]; raw != nil && !ok {
		return fmt.Errorf("field label in ExpensesSchemaJson: required")
	}
	if _, ok := raw["optimization"]; raw != nil && !ok {
		return fmt.Errorf("field optimization in ExpensesSchemaJson: required")
	}
	if _, ok := raw["title"]; raw != nil && !ok {
		return fmt.Errorf("field title in ExpensesSchemaJson: required")
	}
	type Plain ExpensesSchemaJson
	var plain Plain
	if err := json.Unmarshal(value, &plain); err != nil {
		return err
	}
	if matched, _ := regexp.MatchString(`^[A-Z]{3}$`, string(plain.Currency)); !matched {
		return fmt.Errorf("field %s pattern match: must match %s", "Currency", `^[A-Z]{3}$`)
	}
	if utf8.RuneCountInString(string(plain.Description)) > 8000 {
		return fmt.Errorf("field %s length: must be <= %d", "description", 8000)
	}
	if utf8.RuneCountInString(string(plain.Label)) < 1 {
		return fmt.Errorf("field %s length: must be >= %d", "label", 1)
	}
	if utf8.RuneCountInString(string(plain.Label)) > 80 {
		return fmt.Errorf("field %s length: must be <= %d", "label", 80)
	}
	if utf8.RuneCountInString(string(plain.Title)) < 1 {
		return fmt.Errorf("field %s length: must be >= %d", "title", 1)
	}
	if utf8.RuneCountInString(string(plain.Title)) > 160 {
		return fmt.Errorf("field %s length: must be <= %d", "title", 160)
	}
	*j = ExpensesSchemaJson(plain)
	return nil
}

type FixMonthCalculation struct {
	// Amount corresponds to the JSON schema field "amount".
	Amount NonNegativeMoneyAmount `json:"amount" yaml:"amount" mapstructure:"amount"`

	// Type corresponds to the JSON schema field "type".
	Type interface{} `json:"type" yaml:"type" mapstructure:"type"`
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *FixMonthCalculation) UnmarshalJSON(value []byte) error {
	var raw map[string]interface{}
	if err := json.Unmarshal(value, &raw); err != nil {
		return err
	}
	if _, ok := raw["amount"]; raw != nil && !ok {
		return fmt.Errorf("field amount in FixMonthCalculation: required")
	}
	if _, ok := raw["type"]; raw != nil && !ok {
		return fmt.Errorf("field type in FixMonthCalculation: required")
	}
	type Plain FixMonthCalculation
	var plain Plain
	if err := json.Unmarshal(value, &plain); err != nil {
		return err
	}
	*j = FixMonthCalculation(plain)
	return nil
}

type FixYearCalculation struct {
	// Amount corresponds to the JSON schema field "amount".
	Amount NonNegativeMoneyAmount `json:"amount" yaml:"amount" mapstructure:"amount"`

	// Type corresponds to the JSON schema field "type".
	Type interface{} `json:"type" yaml:"type" mapstructure:"type"`
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *FixYearCalculation) UnmarshalJSON(value []byte) error {
	var raw map[string]interface{}
	if err := json.Unmarshal(value, &raw); err != nil {
		return err
	}
	if _, ok := raw["amount"]; raw != nil && !ok {
		return fmt.Errorf("field amount in FixYearCalculation: required")
	}
	if _, ok := raw["type"]; raw != nil && !ok {
		return fmt.Errorf("field type in FixYearCalculation: required")
	}
	type Plain FixYearCalculation
	var plain Plain
	if err := json.Unmarshal(value, &plain); err != nil {
		return err
	}
	*j = FixYearCalculation(plain)
	return nil
}

type GrossAmountFixedRule struct {
	// Amount corresponds to the JSON schema field "amount".
	Amount NonNegativeMoneyAmount `json:"amount" yaml:"amount" mapstructure:"amount"`

	// Type corresponds to the JSON schema field "type".
	Type interface{} `json:"type" yaml:"type" mapstructure:"type"`
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *GrossAmountFixedRule) UnmarshalJSON(value []byte) error {
	var raw map[string]interface{}
	if err := json.Unmarshal(value, &raw); err != nil {
		return err
	}
	if _, ok := raw["amount"]; raw != nil && !ok {
		return fmt.Errorf("field amount in GrossAmountFixedRule: required")
	}
	if _, ok := raw["type"]; raw != nil && !ok {
		return fmt.Errorf("field type in GrossAmountFixedRule: required")
	}
	type Plain GrossAmountFixedRule
	var plain Plain
	if err := json.Unmarshal(value, &plain); err != nil {
		return err
	}
	*j = GrossAmountFixedRule(plain)
	return nil
}

type GrossAmountOptimizedRule struct {
	// Maximum corresponds to the JSON schema field "maximum".
	Maximum MinimumRule `json:"maximum,omitempty,omitzero" yaml:"maximum,omitempty" mapstructure:"maximum,omitempty"`

	// Minimum corresponds to the JSON schema field "minimum".
	Minimum MinimumRule `json:"minimum,omitempty,omitzero" yaml:"minimum,omitempty" mapstructure:"minimum,omitempty"`

	// Type corresponds to the JSON schema field "type".
	Type interface{} `json:"type" yaml:"type" mapstructure:"type"`
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *GrossAmountOptimizedRule) UnmarshalJSON(value []byte) error {
	var raw map[string]interface{}
	if err := json.Unmarshal(value, &raw); err != nil {
		return err
	}
	if _, ok := raw["type"]; raw != nil && !ok {
		return fmt.Errorf("field type in GrossAmountOptimizedRule: required")
	}
	type Plain GrossAmountOptimizedRule
	var plain Plain
	if err := json.Unmarshal(value, &plain); err != nil {
		return err
	}
	*j = GrossAmountOptimizedRule(plain)
	return nil
}

type GrossAmountPercentOfCompanyIncomeRule struct {
	// Percent corresponds to the JSON schema field "percent".
	Percent Percentage `json:"percent" yaml:"percent" mapstructure:"percent"`

	// Type corresponds to the JSON schema field "type".
	Type interface{} `json:"type" yaml:"type" mapstructure:"type"`
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *GrossAmountPercentOfCompanyIncomeRule) UnmarshalJSON(value []byte) error {
	var raw map[string]interface{}
	if err := json.Unmarshal(value, &raw); err != nil {
		return err
	}
	if _, ok := raw["percent"]; raw != nil && !ok {
		return fmt.Errorf("field percent in GrossAmountPercentOfCompanyIncomeRule: required")
	}
	if _, ok := raw["type"]; raw != nil && !ok {
		return fmt.Errorf("field type in GrossAmountPercentOfCompanyIncomeRule: required")
	}
	type Plain GrossAmountPercentOfCompanyIncomeRule
	var plain Plain
	if err := json.Unmarshal(value, &plain); err != nil {
		return err
	}
	*j = GrossAmountPercentOfCompanyIncomeRule(plain)
	return nil
}

// Use the remaining available amount after earlier calculation stages and
// invariants are applied. Application logic defines the exact residual direction
// for salary or dividend.
type GrossAmountResidualRule struct {
	// Description corresponds to the JSON schema field "description".
	Description *string `json:"description,omitempty,omitzero" yaml:"description,omitempty" mapstructure:"description,omitempty"`

	// Type corresponds to the JSON schema field "type".
	Type interface{} `json:"type" yaml:"type" mapstructure:"type"`
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *GrossAmountResidualRule) UnmarshalJSON(value []byte) error {
	var raw map[string]interface{}
	if err := json.Unmarshal(value, &raw); err != nil {
		return err
	}
	if _, ok := raw["type"]; raw != nil && !ok {
		return fmt.Errorf("field type in GrossAmountResidualRule: required")
	}
	type Plain GrossAmountResidualRule
	var plain Plain
	if err := json.Unmarshal(value, &plain); err != nil {
		return err
	}
	if plain.Description != nil && utf8.RuneCountInString(string(*plain.Description)) > 1000 {
		return fmt.Errorf("field %s length: must be <= %d", "description", 1000)
	}
	*j = GrossAmountResidualRule(plain)
	return nil
}

type GrossAmountZeroRule struct {
	// Type corresponds to the JSON schema field "type".
	Type interface{} `json:"type" yaml:"type" mapstructure:"type"`
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *GrossAmountZeroRule) UnmarshalJSON(value []byte) error {
	var raw map[string]interface{}
	if err := json.Unmarshal(value, &raw); err != nil {
		return err
	}
	if _, ok := raw["type"]; raw != nil && !ok {
		return fmt.Errorf("field type in GrossAmountZeroRule: required")
	}
	type Plain GrossAmountZeroRule
	var plain Plain
	if err := json.Unmarshal(value, &plain); err != nil {
		return err
	}
	*j = GrossAmountZeroRule(plain)
	return nil
}

type GrossDividendExpenseRow interface{}

type GrossDividendPercentAboveCapCalculation struct {
	// Basis corresponds to the JSON schema field "basis".
	Basis interface{} `json:"basis" yaml:"basis" mapstructure:"basis"`

	// CapAmount corresponds to the JSON schema field "capAmount".
	CapAmount NonNegativeMoneyAmount `json:"capAmount" yaml:"capAmount" mapstructure:"capAmount"`

	// Percent corresponds to the JSON schema field "percent".
	Percent Percentage `json:"percent" yaml:"percent" mapstructure:"percent"`

	// Type corresponds to the JSON schema field "type".
	Type interface{} `json:"type" yaml:"type" mapstructure:"type"`
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *GrossDividendPercentAboveCapCalculation) UnmarshalJSON(value []byte) error {
	var raw map[string]interface{}
	if err := json.Unmarshal(value, &raw); err != nil {
		return err
	}
	if _, ok := raw["basis"]; raw != nil && !ok {
		return fmt.Errorf("field basis in GrossDividendPercentAboveCapCalculation: required")
	}
	if _, ok := raw["capAmount"]; raw != nil && !ok {
		return fmt.Errorf("field capAmount in GrossDividendPercentAboveCapCalculation: required")
	}
	if _, ok := raw["percent"]; raw != nil && !ok {
		return fmt.Errorf("field percent in GrossDividendPercentAboveCapCalculation: required")
	}
	if _, ok := raw["type"]; raw != nil && !ok {
		return fmt.Errorf("field type in GrossDividendPercentAboveCapCalculation: required")
	}
	type Plain GrossDividendPercentAboveCapCalculation
	var plain Plain
	if err := json.Unmarshal(value, &plain); err != nil {
		return err
	}
	*j = GrossDividendPercentAboveCapCalculation(plain)
	return nil
}

type GrossDividendPercentBelowCapCalculation struct {
	// Basis corresponds to the JSON schema field "basis".
	Basis interface{} `json:"basis" yaml:"basis" mapstructure:"basis"`

	// CapAmount corresponds to the JSON schema field "capAmount".
	CapAmount NonNegativeMoneyAmount `json:"capAmount" yaml:"capAmount" mapstructure:"capAmount"`

	// Percent corresponds to the JSON schema field "percent".
	Percent Percentage `json:"percent" yaml:"percent" mapstructure:"percent"`

	// Type corresponds to the JSON schema field "type".
	Type interface{} `json:"type" yaml:"type" mapstructure:"type"`
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *GrossDividendPercentBelowCapCalculation) UnmarshalJSON(value []byte) error {
	var raw map[string]interface{}
	if err := json.Unmarshal(value, &raw); err != nil {
		return err
	}
	if _, ok := raw["basis"]; raw != nil && !ok {
		return fmt.Errorf("field basis in GrossDividendPercentBelowCapCalculation: required")
	}
	if _, ok := raw["capAmount"]; raw != nil && !ok {
		return fmt.Errorf("field capAmount in GrossDividendPercentBelowCapCalculation: required")
	}
	if _, ok := raw["percent"]; raw != nil && !ok {
		return fmt.Errorf("field percent in GrossDividendPercentBelowCapCalculation: required")
	}
	if _, ok := raw["type"]; raw != nil && !ok {
		return fmt.Errorf("field type in GrossDividendPercentBelowCapCalculation: required")
	}
	type Plain GrossDividendPercentBelowCapCalculation
	var plain Plain
	if err := json.Unmarshal(value, &plain); err != nil {
		return err
	}
	*j = GrossDividendPercentBelowCapCalculation(plain)
	return nil
}

type GrossDividendPercentCalculation struct {
	// Basis corresponds to the JSON schema field "basis".
	Basis interface{} `json:"basis" yaml:"basis" mapstructure:"basis"`

	// Percent corresponds to the JSON schema field "percent".
	Percent Percentage `json:"percent" yaml:"percent" mapstructure:"percent"`

	// Type corresponds to the JSON schema field "type".
	Type interface{} `json:"type" yaml:"type" mapstructure:"type"`
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *GrossDividendPercentCalculation) UnmarshalJSON(value []byte) error {
	var raw map[string]interface{}
	if err := json.Unmarshal(value, &raw); err != nil {
		return err
	}
	if _, ok := raw["basis"]; raw != nil && !ok {
		return fmt.Errorf("field basis in GrossDividendPercentCalculation: required")
	}
	if _, ok := raw["percent"]; raw != nil && !ok {
		return fmt.Errorf("field percent in GrossDividendPercentCalculation: required")
	}
	if _, ok := raw["type"]; raw != nil && !ok {
		return fmt.Errorf("field type in GrossDividendPercentCalculation: required")
	}
	type Plain GrossDividendPercentCalculation
	var plain Plain
	if err := json.Unmarshal(value, &plain); err != nil {
		return err
	}
	*j = GrossDividendPercentCalculation(plain)
	return nil
}

type GrossDividendRule interface{}

type GrossSalaryExpenseRow interface{}

type GrossSalaryPercentAboveCapCalculation struct {
	// Basis corresponds to the JSON schema field "basis".
	Basis interface{} `json:"basis" yaml:"basis" mapstructure:"basis"`

	// CapAmount corresponds to the JSON schema field "capAmount".
	CapAmount NonNegativeMoneyAmount `json:"capAmount" yaml:"capAmount" mapstructure:"capAmount"`

	// Percent corresponds to the JSON schema field "percent".
	Percent Percentage `json:"percent" yaml:"percent" mapstructure:"percent"`

	// Type corresponds to the JSON schema field "type".
	Type interface{} `json:"type" yaml:"type" mapstructure:"type"`
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *GrossSalaryPercentAboveCapCalculation) UnmarshalJSON(value []byte) error {
	var raw map[string]interface{}
	if err := json.Unmarshal(value, &raw); err != nil {
		return err
	}
	if _, ok := raw["basis"]; raw != nil && !ok {
		return fmt.Errorf("field basis in GrossSalaryPercentAboveCapCalculation: required")
	}
	if _, ok := raw["capAmount"]; raw != nil && !ok {
		return fmt.Errorf("field capAmount in GrossSalaryPercentAboveCapCalculation: required")
	}
	if _, ok := raw["percent"]; raw != nil && !ok {
		return fmt.Errorf("field percent in GrossSalaryPercentAboveCapCalculation: required")
	}
	if _, ok := raw["type"]; raw != nil && !ok {
		return fmt.Errorf("field type in GrossSalaryPercentAboveCapCalculation: required")
	}
	type Plain GrossSalaryPercentAboveCapCalculation
	var plain Plain
	if err := json.Unmarshal(value, &plain); err != nil {
		return err
	}
	*j = GrossSalaryPercentAboveCapCalculation(plain)
	return nil
}

type GrossSalaryPercentBelowCapCalculation struct {
	// Basis corresponds to the JSON schema field "basis".
	Basis interface{} `json:"basis" yaml:"basis" mapstructure:"basis"`

	// CapAmount corresponds to the JSON schema field "capAmount".
	CapAmount NonNegativeMoneyAmount `json:"capAmount" yaml:"capAmount" mapstructure:"capAmount"`

	// Percent corresponds to the JSON schema field "percent".
	Percent Percentage `json:"percent" yaml:"percent" mapstructure:"percent"`

	// Type corresponds to the JSON schema field "type".
	Type interface{} `json:"type" yaml:"type" mapstructure:"type"`
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *GrossSalaryPercentBelowCapCalculation) UnmarshalJSON(value []byte) error {
	var raw map[string]interface{}
	if err := json.Unmarshal(value, &raw); err != nil {
		return err
	}
	if _, ok := raw["basis"]; raw != nil && !ok {
		return fmt.Errorf("field basis in GrossSalaryPercentBelowCapCalculation: required")
	}
	if _, ok := raw["capAmount"]; raw != nil && !ok {
		return fmt.Errorf("field capAmount in GrossSalaryPercentBelowCapCalculation: required")
	}
	if _, ok := raw["percent"]; raw != nil && !ok {
		return fmt.Errorf("field percent in GrossSalaryPercentBelowCapCalculation: required")
	}
	if _, ok := raw["type"]; raw != nil && !ok {
		return fmt.Errorf("field type in GrossSalaryPercentBelowCapCalculation: required")
	}
	type Plain GrossSalaryPercentBelowCapCalculation
	var plain Plain
	if err := json.Unmarshal(value, &plain); err != nil {
		return err
	}
	*j = GrossSalaryPercentBelowCapCalculation(plain)
	return nil
}

type GrossSalaryPercentCalculation struct {
	// Basis corresponds to the JSON schema field "basis".
	Basis interface{} `json:"basis" yaml:"basis" mapstructure:"basis"`

	// Percent corresponds to the JSON schema field "percent".
	Percent Percentage `json:"percent" yaml:"percent" mapstructure:"percent"`

	// Type corresponds to the JSON schema field "type".
	Type interface{} `json:"type" yaml:"type" mapstructure:"type"`
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *GrossSalaryPercentCalculation) UnmarshalJSON(value []byte) error {
	var raw map[string]interface{}
	if err := json.Unmarshal(value, &raw); err != nil {
		return err
	}
	if _, ok := raw["basis"]; raw != nil && !ok {
		return fmt.Errorf("field basis in GrossSalaryPercentCalculation: required")
	}
	if _, ok := raw["percent"]; raw != nil && !ok {
		return fmt.Errorf("field percent in GrossSalaryPercentCalculation: required")
	}
	if _, ok := raw["type"]; raw != nil && !ok {
		return fmt.Errorf("field type in GrossSalaryPercentCalculation: required")
	}
	type Plain GrossSalaryPercentCalculation
	var plain Plain
	if err := json.Unmarshal(value, &plain); err != nil {
		return err
	}
	*j = GrossSalaryPercentCalculation(plain)
	return nil
}

type GrossSalaryRule interface{}

type MinimumFixedRule struct {
	// Amount corresponds to the JSON schema field "amount".
	Amount NonNegativeMoneyAmount `json:"amount" yaml:"amount" mapstructure:"amount"`

	// Type corresponds to the JSON schema field "type".
	Type interface{} `json:"type" yaml:"type" mapstructure:"type"`
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *MinimumFixedRule) UnmarshalJSON(value []byte) error {
	var raw map[string]interface{}
	if err := json.Unmarshal(value, &raw); err != nil {
		return err
	}
	if _, ok := raw["amount"]; raw != nil && !ok {
		return fmt.Errorf("field amount in MinimumFixedRule: required")
	}
	if _, ok := raw["type"]; raw != nil && !ok {
		return fmt.Errorf("field type in MinimumFixedRule: required")
	}
	type Plain MinimumFixedRule
	var plain Plain
	if err := json.Unmarshal(value, &plain); err != nil {
		return err
	}
	*j = MinimumFixedRule(plain)
	return nil
}

type MinimumPercentOfCompanyIncomeRule struct {
	// Percent corresponds to the JSON schema field "percent".
	Percent Percentage `json:"percent" yaml:"percent" mapstructure:"percent"`

	// Type corresponds to the JSON schema field "type".
	Type interface{} `json:"type" yaml:"type" mapstructure:"type"`
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *MinimumPercentOfCompanyIncomeRule) UnmarshalJSON(value []byte) error {
	var raw map[string]interface{}
	if err := json.Unmarshal(value, &raw); err != nil {
		return err
	}
	if _, ok := raw["percent"]; raw != nil && !ok {
		return fmt.Errorf("field percent in MinimumPercentOfCompanyIncomeRule: required")
	}
	if _, ok := raw["type"]; raw != nil && !ok {
		return fmt.Errorf("field type in MinimumPercentOfCompanyIncomeRule: required")
	}
	type Plain MinimumPercentOfCompanyIncomeRule
	var plain Plain
	if err := json.Unmarshal(value, &plain); err != nil {
		return err
	}
	*j = MinimumPercentOfCompanyIncomeRule(plain)
	return nil
}

type MinimumRule interface{}

// Human-readable row name. Names are free-form.
type NonEmptyName string

// UnmarshalJSON implements json.Unmarshaler.
func (j *NonEmptyName) UnmarshalJSON(value []byte) error {
	type Plain NonEmptyName
	var plain Plain
	if err := json.Unmarshal(value, &plain); err != nil {
		return err
	}
	if utf8.RuneCountInString(string(plain)) < 1 {
		return fmt.Errorf("field %s length: must be >= %d", "", 1)
	}
	if utf8.RuneCountInString(string(plain)) > 120 {
		return fmt.Errorf("field %s length: must be <= %d", "", 120)
	}
	*j = NonEmptyName(plain)
	return nil
}

// Non-negative money amount in the configuration currency.
type NonNegativeMoneyAmount float64

// UnmarshalJSON implements json.Unmarshaler.
func (j *NonNegativeMoneyAmount) UnmarshalJSON(value []byte) error {
	type Plain NonNegativeMoneyAmount
	var plain Plain
	if err := json.Unmarshal(value, &plain); err != nil {
		return err
	}
	if 0 > plain {
		return fmt.Errorf("field %s: must be >= %v", "", 0)
	}
	*j = NonNegativeMoneyAmount(plain)
	return nil
}

type PercentAboveCapCalculation struct {
	// Basis corresponds to the JSON schema field "basis".
	Basis Basis `json:"basis" yaml:"basis" mapstructure:"basis"`

	// CapAmount corresponds to the JSON schema field "capAmount".
	CapAmount NonNegativeMoneyAmount `json:"capAmount" yaml:"capAmount" mapstructure:"capAmount"`

	// Percent corresponds to the JSON schema field "percent".
	Percent Percentage `json:"percent" yaml:"percent" mapstructure:"percent"`

	// Type corresponds to the JSON schema field "type".
	Type interface{} `json:"type" yaml:"type" mapstructure:"type"`
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *PercentAboveCapCalculation) UnmarshalJSON(value []byte) error {
	var raw map[string]interface{}
	if err := json.Unmarshal(value, &raw); err != nil {
		return err
	}
	if _, ok := raw["basis"]; raw != nil && !ok {
		return fmt.Errorf("field basis in PercentAboveCapCalculation: required")
	}
	if _, ok := raw["capAmount"]; raw != nil && !ok {
		return fmt.Errorf("field capAmount in PercentAboveCapCalculation: required")
	}
	if _, ok := raw["percent"]; raw != nil && !ok {
		return fmt.Errorf("field percent in PercentAboveCapCalculation: required")
	}
	if _, ok := raw["type"]; raw != nil && !ok {
		return fmt.Errorf("field type in PercentAboveCapCalculation: required")
	}
	type Plain PercentAboveCapCalculation
	var plain Plain
	if err := json.Unmarshal(value, &plain); err != nil {
		return err
	}
	*j = PercentAboveCapCalculation(plain)
	return nil
}

type PercentBelowCapCalculation struct {
	// Basis corresponds to the JSON schema field "basis".
	Basis Basis `json:"basis" yaml:"basis" mapstructure:"basis"`

	// CapAmount corresponds to the JSON schema field "capAmount".
	CapAmount NonNegativeMoneyAmount `json:"capAmount" yaml:"capAmount" mapstructure:"capAmount"`

	// Percent corresponds to the JSON schema field "percent".
	Percent Percentage `json:"percent" yaml:"percent" mapstructure:"percent"`

	// Type corresponds to the JSON schema field "type".
	Type interface{} `json:"type" yaml:"type" mapstructure:"type"`
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *PercentBelowCapCalculation) UnmarshalJSON(value []byte) error {
	var raw map[string]interface{}
	if err := json.Unmarshal(value, &raw); err != nil {
		return err
	}
	if _, ok := raw["basis"]; raw != nil && !ok {
		return fmt.Errorf("field basis in PercentBelowCapCalculation: required")
	}
	if _, ok := raw["capAmount"]; raw != nil && !ok {
		return fmt.Errorf("field capAmount in PercentBelowCapCalculation: required")
	}
	if _, ok := raw["percent"]; raw != nil && !ok {
		return fmt.Errorf("field percent in PercentBelowCapCalculation: required")
	}
	if _, ok := raw["type"]; raw != nil && !ok {
		return fmt.Errorf("field type in PercentBelowCapCalculation: required")
	}
	type Plain PercentBelowCapCalculation
	var plain Plain
	if err := json.Unmarshal(value, &plain); err != nil {
		return err
	}
	*j = PercentBelowCapCalculation(plain)
	return nil
}

type PercentCalculation struct {
	// Basis corresponds to the JSON schema field "basis".
	Basis Basis `json:"basis" yaml:"basis" mapstructure:"basis"`

	// Percent corresponds to the JSON schema field "percent".
	Percent Percentage `json:"percent" yaml:"percent" mapstructure:"percent"`

	// Type corresponds to the JSON schema field "type".
	Type interface{} `json:"type" yaml:"type" mapstructure:"type"`
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *PercentCalculation) UnmarshalJSON(value []byte) error {
	var raw map[string]interface{}
	if err := json.Unmarshal(value, &raw); err != nil {
		return err
	}
	if _, ok := raw["basis"]; raw != nil && !ok {
		return fmt.Errorf("field basis in PercentCalculation: required")
	}
	if _, ok := raw["percent"]; raw != nil && !ok {
		return fmt.Errorf("field percent in PercentCalculation: required")
	}
	if _, ok := raw["type"]; raw != nil && !ok {
		return fmt.Errorf("field type in PercentCalculation: required")
	}
	type Plain PercentCalculation
	var plain Plain
	if err := json.Unmarshal(value, &plain); err != nil {
		return err
	}
	*j = PercentCalculation(plain)
	return nil
}

// Percentage between 0 and 100. Use 10 for 10%, not 0.10.
type Percentage float64

// UnmarshalJSON implements json.Unmarshaler.
func (j *Percentage) UnmarshalJSON(value []byte) error {
	type Plain Percentage
	var plain Plain
	if err := json.Unmarshal(value, &plain); err != nil {
		return err
	}
	if 100 < plain {
		return fmt.Errorf("field %s: must be <= %v", "", 100)
	}
	if 0 > plain {
		return fmt.Errorf("field %s: must be >= %v", "", 0)
	}
	*j = Percentage(plain)
	return nil
}

// Positive money amount in the configuration currency.
type PositiveMoneyAmount float64

// UnmarshalJSON implements json.Unmarshaler.
func (j *PositiveMoneyAmount) UnmarshalJSON(value []byte) error {
	type Plain PositiveMoneyAmount
	var plain Plain
	if err := json.Unmarshal(value, &plain); err != nil {
		return err
	}
	if 0 >= plain {
		return fmt.Errorf("field %s: must be > %v", "", 0)
	}
	*j = PositiveMoneyAmount(plain)
	return nil
}

type RowCommon struct {
	// Calculation corresponds to the JSON schema field "calculation".
	Calculation interface{} `json:"calculation" yaml:"calculation" mapstructure:"calculation"`

	// Description corresponds to the JSON schema field "description".
	Description *string `json:"description,omitempty,omitzero" yaml:"description,omitempty" mapstructure:"description,omitempty"`

	// Name corresponds to the JSON schema field "name".
	Name NonEmptyName `json:"name" yaml:"name" mapstructure:"name"`
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *RowCommon) UnmarshalJSON(value []byte) error {
	var raw map[string]interface{}
	if err := json.Unmarshal(value, &raw); err != nil {
		return err
	}
	if _, ok := raw["calculation"]; raw != nil && !ok {
		return fmt.Errorf("field calculation in RowCommon: required")
	}
	if _, ok := raw["name"]; raw != nil && !ok {
		return fmt.Errorf("field name in RowCommon: required")
	}
	type Plain RowCommon
	var plain Plain
	if err := json.Unmarshal(value, &plain); err != nil {
		return err
	}
	if plain.Description != nil && utf8.RuneCountInString(string(*plain.Description)) > 2000 {
		return fmt.Errorf("field %s length: must be <= %d", "description", 2000)
	}
	*j = RowCommon(plain)
	return nil
}

type SettingsSchemaJson struct {
	// AppName corresponds to the JSON schema field "appName".
	AppName string `json:"appName" yaml:"appName" mapstructure:"appName"`
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *SettingsSchemaJson) UnmarshalJSON(value []byte) error {
	var raw map[string]interface{}
	if err := json.Unmarshal(value, &raw); err != nil {
		return err
	}
	if _, ok := raw["appName"]; raw != nil && !ok {
		return fmt.Errorf("field appName in SettingsSchemaJson: required")
	}
	type Plain SettingsSchemaJson
	var plain Plain
	if err := json.Unmarshal(value, &plain); err != nil {
		return err
	}
	if utf8.RuneCountInString(string(plain.AppName)) < 1 {
		return fmt.Errorf("field %s length: must be >= %d", "appName", 1)
	}
	*j = SettingsSchemaJson(plain)
	return nil
}
