// Code generated by github.com/atombender/go-jsonschema, DO NOT EDIT.

package main

import "encoding/json"
import "fmt"
import "reflect"
import "regexp"
import "unicode/utf8"

type Basis string

const BasisCompanyIncome Basis = "companyIncome"
const BasisCompanyProfit Basis = "companyProfit"
const BasisGrossDividend Basis = "grossDividend"
const BasisGrossSalary Basis = "grossSalary"

var enumValues_Basis = []interface{}{
	"companyIncome",
	"companyProfit",
	"grossSalary",
	"grossDividend",
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *Basis) UnmarshalJSON(value []byte) error {
	var v string
	if err := json.Unmarshal(value, &v); err != nil {
		return err
	}
	var ok bool
	for _, expected := range enumValues_Basis {
		if reflect.DeepEqual(v, expected) {
			ok = true
			break
		}
	}
	if !ok {
		return fmt.Errorf("invalid value (expected one of %#v): %#v", enumValues_Basis, v)
	}
	*j = Basis(v)
	return nil
}

type CompanyIncomeExpenseRow interface{}

type CompanyIncomeOrSalaryBasis string

const CompanyIncomeOrSalaryBasisCompanyIncome CompanyIncomeOrSalaryBasis = "companyIncome"
const CompanyIncomeOrSalaryBasisGrossSalary CompanyIncomeOrSalaryBasis = "grossSalary"

var enumValues_CompanyIncomeOrSalaryBasis = []interface{}{
	"companyIncome",
	"grossSalary",
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *CompanyIncomeOrSalaryBasis) UnmarshalJSON(value []byte) error {
	var v string
	if err := json.Unmarshal(value, &v); err != nil {
		return err
	}
	var ok bool
	for _, expected := range enumValues_CompanyIncomeOrSalaryBasis {
		if reflect.DeepEqual(v, expected) {
			ok = true
			break
		}
	}
	if !ok {
		return fmt.Errorf("invalid value (expected one of %#v): %#v", enumValues_CompanyIncomeOrSalaryBasis, v)
	}
	*j = CompanyIncomeOrSalaryBasis(v)
	return nil
}

type CompanyIncomeOrSalaryPercentAboveCapCalculation struct {
	// Basis corresponds to the JSON schema field "basis".
	Basis CompanyIncomeOrSalaryBasis `json:"basis" yaml:"basis" mapstructure:"basis"`

	// CapAmount corresponds to the JSON schema field "capAmount".
	CapAmount NonNegativeMoneyAmount `json:"capAmount" yaml:"capAmount" mapstructure:"capAmount"`

	// Percent corresponds to the JSON schema field "percent".
	Percent Percentage `json:"percent" yaml:"percent" mapstructure:"percent"`

	// Type corresponds to the JSON schema field "type".
	Type interface{} `json:"type" yaml:"type" mapstructure:"type"`
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *CompanyIncomeOrSalaryPercentAboveCapCalculation) UnmarshalJSON(value []byte) error {
	var raw map[string]interface{}
	if err := json.Unmarshal(value, &raw); err != nil {
		return err
	}
	if _, ok := raw["basis"]; raw != nil && !ok {
		return fmt.Errorf("field basis in CompanyIncomeOrSalaryPercentAboveCapCalculation: required")
	}
	if _, ok := raw["capAmount"]; raw != nil && !ok {
		return fmt.Errorf("field capAmount in CompanyIncomeOrSalaryPercentAboveCapCalculation: required")
	}
	if _, ok := raw["percent"]; raw != nil && !ok {
		return fmt.Errorf("field percent in CompanyIncomeOrSalaryPercentAboveCapCalculation: required")
	}
	if _, ok := raw["type"]; raw != nil && !ok {
		return fmt.Errorf("field type in CompanyIncomeOrSalaryPercentAboveCapCalculation: required")
	}
	type Plain CompanyIncomeOrSalaryPercentAboveCapCalculation
	var plain Plain
	if err := json.Unmarshal(value, &plain); err != nil {
		return err
	}
	*j = CompanyIncomeOrSalaryPercentAboveCapCalculation(plain)
	return nil
}

type CompanyIncomeOrSalaryPercentBelowCapCalculation struct {
	// Basis corresponds to the JSON schema field "basis".
	Basis CompanyIncomeOrSalaryBasis `json:"basis" yaml:"basis" mapstructure:"basis"`

	// CapAmount corresponds to the JSON schema field "capAmount".
	CapAmount NonNegativeMoneyAmount `json:"capAmount" yaml:"capAmount" mapstructure:"capAmount"`

	// Percent corresponds to the JSON schema field "percent".
	Percent Percentage `json:"percent" yaml:"percent" mapstructure:"percent"`

	// Type corresponds to the JSON schema field "type".
	Type interface{} `json:"type" yaml:"type" mapstructure:"type"`
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *CompanyIncomeOrSalaryPercentBelowCapCalculation) UnmarshalJSON(value []byte) error {
	var raw map[string]interface{}
	if err := json.Unmarshal(value, &raw); err != nil {
		return err
	}
	if _, ok := raw["basis"]; raw != nil && !ok {
		return fmt.Errorf("field basis in CompanyIncomeOrSalaryPercentBelowCapCalculation: required")
	}
	if _, ok := raw["capAmount"]; raw != nil && !ok {
		return fmt.Errorf("field capAmount in CompanyIncomeOrSalaryPercentBelowCapCalculation: required")
	}
	if _, ok := raw["percent"]; raw != nil && !ok {
		return fmt.Errorf("field percent in CompanyIncomeOrSalaryPercentBelowCapCalculation: required")
	}
	if _, ok := raw["type"]; raw != nil && !ok {
		return fmt.Errorf("field type in CompanyIncomeOrSalaryPercentBelowCapCalculation: required")
	}
	type Plain CompanyIncomeOrSalaryPercentBelowCapCalculation
	var plain Plain
	if err := json.Unmarshal(value, &plain); err != nil {
		return err
	}
	*j = CompanyIncomeOrSalaryPercentBelowCapCalculation(plain)
	return nil
}

type CompanyIncomeOrSalaryPercentCalculation struct {
	// Basis corresponds to the JSON schema field "basis".
	Basis CompanyIncomeOrSalaryBasis `json:"basis" yaml:"basis" mapstructure:"basis"`

	// Percent corresponds to the JSON schema field "percent".
	Percent Percentage `json:"percent" yaml:"percent" mapstructure:"percent"`

	// Type corresponds to the JSON schema field "type".
	Type interface{} `json:"type" yaml:"type" mapstructure:"type"`
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *CompanyIncomeOrSalaryPercentCalculation) UnmarshalJSON(value []byte) error {
	var raw map[string]interface{}
	if err := json.Unmarshal(value, &raw); err != nil {
		return err
	}
	if _, ok := raw["basis"]; raw != nil && !ok {
		return fmt.Errorf("field basis in CompanyIncomeOrSalaryPercentCalculation: required")
	}
	if _, ok := raw["percent"]; raw != nil && !ok {
		return fmt.Errorf("field percent in CompanyIncomeOrSalaryPercentCalculation: required")
	}
	if _, ok := raw["type"]; raw != nil && !ok {
		return fmt.Errorf("field type in CompanyIncomeOrSalaryPercentCalculation: required")
	}
	type Plain CompanyIncomeOrSalaryPercentCalculation
	var plain Plain
	if err := json.Unmarshal(value, &plain); err != nil {
		return err
	}
	*j = CompanyIncomeOrSalaryPercentCalculation(plain)
	return nil
}

type CompanyProfitExpenseRow interface{}

type CompanyProfitOrSalaryBasis string

const CompanyProfitOrSalaryBasisCompanyProfit CompanyProfitOrSalaryBasis = "companyProfit"
const CompanyProfitOrSalaryBasisGrossSalary CompanyProfitOrSalaryBasis = "grossSalary"

var enumValues_CompanyProfitOrSalaryBasis = []interface{}{
	"companyProfit",
	"grossSalary",
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *CompanyProfitOrSalaryBasis) UnmarshalJSON(value []byte) error {
	var v string
	if err := json.Unmarshal(value, &v); err != nil {
		return err
	}
	var ok bool
	for _, expected := range enumValues_CompanyProfitOrSalaryBasis {
		if reflect.DeepEqual(v, expected) {
			ok = true
			break
		}
	}
	if !ok {
		return fmt.Errorf("invalid value (expected one of %#v): %#v", enumValues_CompanyProfitOrSalaryBasis, v)
	}
	*j = CompanyProfitOrSalaryBasis(v)
	return nil
}

type CompanyProfitOrSalaryPercentAboveCapCalculation struct {
	// Basis corresponds to the JSON schema field "basis".
	Basis CompanyProfitOrSalaryBasis `json:"basis" yaml:"basis" mapstructure:"basis"`

	// CapAmount corresponds to the JSON schema field "capAmount".
	CapAmount NonNegativeMoneyAmount `json:"capAmount" yaml:"capAmount" mapstructure:"capAmount"`

	// Percent corresponds to the JSON schema field "percent".
	Percent Percentage `json:"percent" yaml:"percent" mapstructure:"percent"`

	// Type corresponds to the JSON schema field "type".
	Type interface{} `json:"type" yaml:"type" mapstructure:"type"`
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *CompanyProfitOrSalaryPercentAboveCapCalculation) UnmarshalJSON(value []byte) error {
	var raw map[string]interface{}
	if err := json.Unmarshal(value, &raw); err != nil {
		return err
	}
	if _, ok := raw["basis"]; raw != nil && !ok {
		return fmt.Errorf("field basis in CompanyProfitOrSalaryPercentAboveCapCalculation: required")
	}
	if _, ok := raw["capAmount"]; raw != nil && !ok {
		return fmt.Errorf("field capAmount in CompanyProfitOrSalaryPercentAboveCapCalculation: required")
	}
	if _, ok := raw["percent"]; raw != nil && !ok {
		return fmt.Errorf("field percent in CompanyProfitOrSalaryPercentAboveCapCalculation: required")
	}
	if _, ok := raw["type"]; raw != nil && !ok {
		return fmt.Errorf("field type in CompanyProfitOrSalaryPercentAboveCapCalculation: required")
	}
	type Plain CompanyProfitOrSalaryPercentAboveCapCalculation
	var plain Plain
	if err := json.Unmarshal(value, &plain); err != nil {
		return err
	}
	*j = CompanyProfitOrSalaryPercentAboveCapCalculation(plain)
	return nil
}

type CompanyProfitOrSalaryPercentBelowCapCalculation struct {
	// Basis corresponds to the JSON schema field "basis".
	Basis CompanyProfitOrSalaryBasis `json:"basis" yaml:"basis" mapstructure:"basis"`

	// CapAmount corresponds to the JSON schema field "capAmount".
	CapAmount NonNegativeMoneyAmount `json:"capAmount" yaml:"capAmount" mapstructure:"capAmount"`

	// Percent corresponds to the JSON schema field "percent".
	Percent Percentage `json:"percent" yaml:"percent" mapstructure:"percent"`

	// Type corresponds to the JSON schema field "type".
	Type interface{} `json:"type" yaml:"type" mapstructure:"type"`
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *CompanyProfitOrSalaryPercentBelowCapCalculation) UnmarshalJSON(value []byte) error {
	var raw map[string]interface{}
	if err := json.Unmarshal(value, &raw); err != nil {
		return err
	}
	if _, ok := raw["basis"]; raw != nil && !ok {
		return fmt.Errorf("field basis in CompanyProfitOrSalaryPercentBelowCapCalculation: required")
	}
	if _, ok := raw["capAmount"]; raw != nil && !ok {
		return fmt.Errorf("field capAmount in CompanyProfitOrSalaryPercentBelowCapCalculation: required")
	}
	if _, ok := raw["percent"]; raw != nil && !ok {
		return fmt.Errorf("field percent in CompanyProfitOrSalaryPercentBelowCapCalculation: required")
	}
	if _, ok := raw["type"]; raw != nil && !ok {
		return fmt.Errorf("field type in CompanyProfitOrSalaryPercentBelowCapCalculation: required")
	}
	type Plain CompanyProfitOrSalaryPercentBelowCapCalculation
	var plain Plain
	if err := json.Unmarshal(value, &plain); err != nil {
		return err
	}
	*j = CompanyProfitOrSalaryPercentBelowCapCalculation(plain)
	return nil
}

type CompanyProfitOrSalaryPercentCalculation struct {
	// Basis corresponds to the JSON schema field "basis".
	Basis CompanyProfitOrSalaryBasis `json:"basis" yaml:"basis" mapstructure:"basis"`

	// Percent corresponds to the JSON schema field "percent".
	Percent Percentage `json:"percent" yaml:"percent" mapstructure:"percent"`

	// Type corresponds to the JSON schema field "type".
	Type interface{} `json:"type" yaml:"type" mapstructure:"type"`
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *CompanyProfitOrSalaryPercentCalculation) UnmarshalJSON(value []byte) error {
	var raw map[string]interface{}
	if err := json.Unmarshal(value, &raw); err != nil {
		return err
	}
	if _, ok := raw["basis"]; raw != nil && !ok {
		return fmt.Errorf("field basis in CompanyProfitOrSalaryPercentCalculation: required")
	}
	if _, ok := raw["percent"]; raw != nil && !ok {
		return fmt.Errorf("field percent in CompanyProfitOrSalaryPercentCalculation: required")
	}
	if _, ok := raw["type"]; raw != nil && !ok {
		return fmt.Errorf("field type in CompanyProfitOrSalaryPercentCalculation: required")
	}
	type Plain CompanyProfitOrSalaryPercentCalculation
	var plain Plain
	if err := json.Unmarshal(value, &plain); err != nil {
		return err
	}
	*j = CompanyProfitOrSalaryPercentCalculation(plain)
	return nil
}

// Configuration schema for the expense, salary/dividend, and one-target
// optimization model used by Income Atlas. The model is intentionally
// spreadsheet-like: company income is calculated elsewhere, then configurable
// expense rows are applied in four ordered groups. The final optimization target
// is normally total usable income, which is net salary plus net dividend. This
// schema is restrictive about allowed calculation modes, percentages, and
// non-negative money amounts, while still allowing freely named rows and
// country-specific combinations.
type ExpensesSchemaJson struct {
	// Hard constraints checked after each candidate calculation. Constraints should
	// invalidate a candidate, not change its computed values.
	Constraints ExpensesSchemaJsonConstraints `json:"constraints" yaml:"constraints" mapstructure:"constraints"`

	// Main currency for all fixed amounts in this configuration. Use an ISO 4217
	// currency code. The schema only validates the shape, not whether the code
	// exists.
	Currency string `json:"currency" yaml:"currency" mapstructure:"currency"`

	// The four ordered groups of expenses/deductions used by the model. Each group
	// contains freely named rows. The row's calculation type determines how the
	// amount is calculated. The same row shape is used everywhere, but each group
	// only allows basis values that make sense for that group.
	ExpenseGroups ExpensesSchemaJsonExpenseGroups `json:"expenseGroups" yaml:"expenseGroups" mapstructure:"expenseGroups"`

	// One-target optimization configuration. Only one main target may be optimized at
	// once. All other values should be fixed, residual, minimums, maximums, or
	// constraints. The normal target is 'totalUsableIncome', meaning net salary plus
	// net dividend.
	Optimization ExpensesSchemaJsonOptimization `json:"optimization" yaml:"optimization" mapstructure:"optimization"`

	// Version of this settings document. This is not the JSON Schema version; it is
	// the application configuration version. Use a semantic or date-like version such
	// as '1.0.0'.
	Version string `json:"version" yaml:"version" mapstructure:"version"`
}

// Hard constraints checked after each candidate calculation. Constraints should
// invalidate a candidate, not change its computed values.
type ExpensesSchemaJsonConstraints struct {
	// Maximum gross dividend relative to gross salary. This is useful for
	// countries/profiles where excessive dividends compared to salary are restricted
	// or risky. Example: 10 means gross dividend may not exceed 10% of gross salary.
	// Use mode 'disabled' if no such restriction exists. When gross salary is zero
	// and this constraint is enabled, the application should treat any positive
	// dividend as invalid unless it explicitly implements another fallback rule.
	MaximumDividendToSalaryPercent interface{} `json:"maximumDividendToSalaryPercent" yaml:"maximumDividendToSalaryPercent" mapstructure:"maximumDividendToSalaryPercent"`

	// Minimum gross salary constraint. Use mode 'fixed' for a hard minimum salary
	// amount. Use mode 'percentOfCompanyIncome' if the minimum salary should be
	// derived from company income. Use mode 'disabled' if there is no minimum salary
	// constraint.
	MinimumGrossSalary MinimumRule `json:"minimumGrossSalary" yaml:"minimumGrossSalary" mapstructure:"minimumGrossSalary"`
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *ExpensesSchemaJsonConstraints) UnmarshalJSON(value []byte) error {
	var raw map[string]interface{}
	if err := json.Unmarshal(value, &raw); err != nil {
		return err
	}
	if _, ok := raw["maximumDividendToSalaryPercent"]; raw != nil && !ok {
		return fmt.Errorf("field maximumDividendToSalaryPercent in ExpensesSchemaJsonConstraints: required")
	}
	if _, ok := raw["minimumGrossSalary"]; raw != nil && !ok {
		return fmt.Errorf("field minimumGrossSalary in ExpensesSchemaJsonConstraints: required")
	}
	type Plain ExpensesSchemaJsonConstraints
	var plain Plain
	if err := json.Unmarshal(value, &plain); err != nil {
		return err
	}
	*j = ExpensesSchemaJsonConstraints(plain)
	return nil
}

// The four ordered groups of expenses/deductions used by the model. Each group
// contains freely named rows. The row's calculation type determines how the amount
// is calculated. The same row shape is used everywhere, but each group only allows
// basis values that make sense for that group.
type ExpensesSchemaJsonExpenseGroups struct {
	// Pre-profit company-side expenses. These are subtracted from company income
	// before company profit is calculated. Typical examples: fixed monthly costs,
	// fixed yearly costs, percentage of company income, gross salary itself, and
	// employer-side salary costs based on gross salary. Employee-side salary
	// deductions do not belong here.
	CompanyIncomeExpenses []CompanyIncomeExpenseRow `json:"companyIncomeExpenses" yaml:"companyIncomeExpenses" mapstructure:"companyIncomeExpenses"`

	// Profit-level company-side expenses. These are subtracted from company profit to
	// calculate company total before/after dividend logic. Typical examples:
	// corporate profit tax, forced company reserve based on profit, fixed
	// profit-level charges, or a gross salary row if a country/profile intentionally
	// models a salary-like value at this stage. In the usual model, gross salary
	// belongs in companyIncomeExpenses, not here.
	CompanyProfitExpenses []CompanyProfitExpenseRow `json:"companyProfitExpenses" yaml:"companyProfitExpenses" mapstructure:"companyProfitExpenses"`

	// Personal deductions from gross dividend. These rows reduce gross dividend to
	// net dividend. Typical examples: dividend tax and dividend-related health/social
	// contributions.
	GrossDividendExpenses []GrossDividendExpenseRow `json:"grossDividendExpenses" yaml:"grossDividendExpenses" mapstructure:"grossDividendExpenses"`

	// Personal deductions from gross salary. These rows reduce gross salary to net
	// salary. Typical examples: employee-side social contributions, employee-side
	// health insurance, and salary income tax. Employer-side salary costs do not
	// belong here because they are company expenses, not deductions from the
	// employee's gross salary.
	GrossSalaryExpenses []GrossSalaryExpenseRow `json:"grossSalaryExpenses" yaml:"grossSalaryExpenses" mapstructure:"grossSalaryExpenses"`
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *ExpensesSchemaJsonExpenseGroups) UnmarshalJSON(value []byte) error {
	var raw map[string]interface{}
	if err := json.Unmarshal(value, &raw); err != nil {
		return err
	}
	if _, ok := raw["companyIncomeExpenses"]; raw != nil && !ok {
		return fmt.Errorf("field companyIncomeExpenses in ExpensesSchemaJsonExpenseGroups: required")
	}
	if _, ok := raw["companyProfitExpenses"]; raw != nil && !ok {
		return fmt.Errorf("field companyProfitExpenses in ExpensesSchemaJsonExpenseGroups: required")
	}
	if _, ok := raw["grossDividendExpenses"]; raw != nil && !ok {
		return fmt.Errorf("field grossDividendExpenses in ExpensesSchemaJsonExpenseGroups: required")
	}
	if _, ok := raw["grossSalaryExpenses"]; raw != nil && !ok {
		return fmt.Errorf("field grossSalaryExpenses in ExpensesSchemaJsonExpenseGroups: required")
	}
	type Plain ExpensesSchemaJsonExpenseGroups
	var plain Plain
	if err := json.Unmarshal(value, &plain); err != nil {
		return err
	}
	if v, ok := raw["companyIncomeExpenses"]; !ok || v == nil {
		plain.CompanyIncomeExpenses = []CompanyIncomeExpenseRow{}
	}
	if v, ok := raw["companyProfitExpenses"]; !ok || v == nil {
		plain.CompanyProfitExpenses = []CompanyProfitExpenseRow{}
	}
	if v, ok := raw["grossDividendExpenses"]; !ok || v == nil {
		plain.GrossDividendExpenses = []GrossDividendExpenseRow{}
	}
	if v, ok := raw["grossSalaryExpenses"]; !ok || v == nil {
		plain.GrossSalaryExpenses = []GrossSalaryExpenseRow{}
	}
	*j = ExpensesSchemaJsonExpenseGroups(plain)
	return nil
}

// One-target optimization configuration. Only one main target may be optimized at
// once. All other values should be fixed, residual, minimums, maximums, or
// constraints. The normal target is 'totalUsableIncome', meaning net salary plus
// net dividend.
type ExpensesSchemaJsonOptimization struct {
	// How gross dividend should be handled. 'residual' means dividend is derived from
	// remaining company money after company expenses, profit expenses, and required
	// company total. This is the recommended default because it avoids invalid
	// salary/dividend combinations. 'fixed' means the value is supplied elsewhere.
	// 'optimized' means the optimizer may vary it directly. 'zero' disables
	// dividends.
	GrossDividendMode ExpensesSchemaJsonOptimizationGrossDividendMode `json:"grossDividendMode,omitempty,omitzero" yaml:"grossDividendMode,omitempty" mapstructure:"grossDividendMode,omitempty"`

	// The single value the optimizer should maximize. Use 'totalUsableIncome' for the
	// usual goal: maximize net salary plus net dividend. 'grossDividend',
	// 'grossSalary', and 'companyTotal' are supported for scenario exploration, but
	// they are not normally the economic target.
	MainTarget ExpensesSchemaJsonOptimizationMainTarget `json:"mainTarget" yaml:"mainTarget" mapstructure:"mainTarget"`

	// Optional lower bounds for optimization outputs. These are constraints, not
	// targets. Each minimum can be disabled, fixed, or expressed as a percentage of
	// company income. For example, companyTotal can be required to stay at least 10%
	// of company income, while grossSalary can have a fixed minimum.
	Minimums ExpensesSchemaJsonOptimizationMinimums `json:"minimums" yaml:"minimums" mapstructure:"minimums"`

	// Optional search settings for a simple scenario/enumeration optimizer. This does
	// not define tax logic; it only controls how candidate gross salaries are
	// generated. A small step gives more precision but more calculations. Explicit
	// candidate points are useful for caps and thresholds where the optimum often
	// sits.
	SalarySearch *ExpensesSchemaJsonOptimizationSalarySearch `json:"salarySearch,omitempty,omitzero" yaml:"salarySearch,omitempty" mapstructure:"salarySearch,omitempty"`
}

type ExpensesSchemaJsonOptimizationGrossDividendMode string

const ExpensesSchemaJsonOptimizationGrossDividendModeFixed ExpensesSchemaJsonOptimizationGrossDividendMode = "fixed"
const ExpensesSchemaJsonOptimizationGrossDividendModeOptimized ExpensesSchemaJsonOptimizationGrossDividendMode = "optimized"
const ExpensesSchemaJsonOptimizationGrossDividendModeResidual ExpensesSchemaJsonOptimizationGrossDividendMode = "residual"
const ExpensesSchemaJsonOptimizationGrossDividendModeZero ExpensesSchemaJsonOptimizationGrossDividendMode = "zero"

var enumValues_ExpensesSchemaJsonOptimizationGrossDividendMode = []interface{}{
	"residual",
	"fixed",
	"optimized",
	"zero",
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *ExpensesSchemaJsonOptimizationGrossDividendMode) UnmarshalJSON(value []byte) error {
	var v string
	if err := json.Unmarshal(value, &v); err != nil {
		return err
	}
	var ok bool
	for _, expected := range enumValues_ExpensesSchemaJsonOptimizationGrossDividendMode {
		if reflect.DeepEqual(v, expected) {
			ok = true
			break
		}
	}
	if !ok {
		return fmt.Errorf("invalid value (expected one of %#v): %#v", enumValues_ExpensesSchemaJsonOptimizationGrossDividendMode, v)
	}
	*j = ExpensesSchemaJsonOptimizationGrossDividendMode(v)
	return nil
}

type ExpensesSchemaJsonOptimizationMainTarget string

const ExpensesSchemaJsonOptimizationMainTargetCompanyTotal ExpensesSchemaJsonOptimizationMainTarget = "companyTotal"
const ExpensesSchemaJsonOptimizationMainTargetGrossDividend ExpensesSchemaJsonOptimizationMainTarget = "grossDividend"
const ExpensesSchemaJsonOptimizationMainTargetGrossSalary ExpensesSchemaJsonOptimizationMainTarget = "grossSalary"
const ExpensesSchemaJsonOptimizationMainTargetTotalUsableIncome ExpensesSchemaJsonOptimizationMainTarget = "totalUsableIncome"

var enumValues_ExpensesSchemaJsonOptimizationMainTarget = []interface{}{
	"totalUsableIncome",
	"grossDividend",
	"grossSalary",
	"companyTotal",
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *ExpensesSchemaJsonOptimizationMainTarget) UnmarshalJSON(value []byte) error {
	var v string
	if err := json.Unmarshal(value, &v); err != nil {
		return err
	}
	var ok bool
	for _, expected := range enumValues_ExpensesSchemaJsonOptimizationMainTarget {
		if reflect.DeepEqual(v, expected) {
			ok = true
			break
		}
	}
	if !ok {
		return fmt.Errorf("invalid value (expected one of %#v): %#v", enumValues_ExpensesSchemaJsonOptimizationMainTarget, v)
	}
	*j = ExpensesSchemaJsonOptimizationMainTarget(v)
	return nil
}

// Optional lower bounds for optimization outputs. These are constraints, not
// targets. Each minimum can be disabled, fixed, or expressed as a percentage of
// company income. For example, companyTotal can be required to stay at least 10%
// of company income, while grossSalary can have a fixed minimum.
type ExpensesSchemaJsonOptimizationMinimums struct {
	// CompanyTotal corresponds to the JSON schema field "companyTotal".
	CompanyTotal MinimumRule `json:"companyTotal" yaml:"companyTotal" mapstructure:"companyTotal"`

	// GrossDividend corresponds to the JSON schema field "grossDividend".
	GrossDividend MinimumRule `json:"grossDividend" yaml:"grossDividend" mapstructure:"grossDividend"`

	// GrossSalary corresponds to the JSON schema field "grossSalary".
	GrossSalary MinimumRule `json:"grossSalary" yaml:"grossSalary" mapstructure:"grossSalary"`

	// TotalUsableIncome corresponds to the JSON schema field "totalUsableIncome".
	TotalUsableIncome MinimumRule `json:"totalUsableIncome" yaml:"totalUsableIncome" mapstructure:"totalUsableIncome"`
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *ExpensesSchemaJsonOptimizationMinimums) UnmarshalJSON(value []byte) error {
	var raw map[string]interface{}
	if err := json.Unmarshal(value, &raw); err != nil {
		return err
	}
	if _, ok := raw["companyTotal"]; raw != nil && !ok {
		return fmt.Errorf("field companyTotal in ExpensesSchemaJsonOptimizationMinimums: required")
	}
	if _, ok := raw["grossDividend"]; raw != nil && !ok {
		return fmt.Errorf("field grossDividend in ExpensesSchemaJsonOptimizationMinimums: required")
	}
	if _, ok := raw["grossSalary"]; raw != nil && !ok {
		return fmt.Errorf("field grossSalary in ExpensesSchemaJsonOptimizationMinimums: required")
	}
	if _, ok := raw["totalUsableIncome"]; raw != nil && !ok {
		return fmt.Errorf("field totalUsableIncome in ExpensesSchemaJsonOptimizationMinimums: required")
	}
	type Plain ExpensesSchemaJsonOptimizationMinimums
	var plain Plain
	if err := json.Unmarshal(value, &plain); err != nil {
		return err
	}
	*j = ExpensesSchemaJsonOptimizationMinimums(plain)
	return nil
}

// Optional search settings for a simple scenario/enumeration optimizer. This does
// not define tax logic; it only controls how candidate gross salaries are
// generated. A small step gives more precision but more calculations. Explicit
// candidate points are useful for caps and thresholds where the optimum often
// sits.
type ExpensesSchemaJsonOptimizationSalarySearch struct {
	// Whether the optimizer may vary gross salary. If false, the application should
	// use whatever gross salary is provided elsewhere.
	Enabled bool `json:"enabled,omitempty,omitzero" yaml:"enabled,omitempty" mapstructure:"enabled,omitempty"`

	// Additional gross salary candidates that should always be tested, such as 0,
	// minimum salary, contribution caps, or legal threshold values. Values must be
	// non-negative.
	ExplicitCandidateAmounts []NonNegativeMoneyAmount `json:"explicitCandidateAmounts,omitempty,omitzero" yaml:"explicitCandidateAmounts,omitempty" mapstructure:"explicitCandidateAmounts,omitempty"`

	// Increment used when enumerating candidate gross salaries. Example: 50 or 100.
	// The schema allows zero because some applications may ignore this field when
	// explicit candidate points are used, but a practical optimizer should use a
	// positive value.
	StepAmount *NonNegativeMoneyAmount `json:"stepAmount,omitempty,omitzero" yaml:"stepAmount,omitempty" mapstructure:"stepAmount,omitempty"`
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *ExpensesSchemaJsonOptimizationSalarySearch) UnmarshalJSON(value []byte) error {
	var raw map[string]interface{}
	if err := json.Unmarshal(value, &raw); err != nil {
		return err
	}
	type Plain ExpensesSchemaJsonOptimizationSalarySearch
	var plain Plain
	if err := json.Unmarshal(value, &plain); err != nil {
		return err
	}
	if v, ok := raw["enabled"]; !ok || v == nil {
		plain.Enabled = true
	}
	if v, ok := raw["explicitCandidateAmounts"]; !ok || v == nil {
		plain.ExplicitCandidateAmounts = []NonNegativeMoneyAmount{}
	}
	*j = ExpensesSchemaJsonOptimizationSalarySearch(plain)
	return nil
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *ExpensesSchemaJsonOptimization) UnmarshalJSON(value []byte) error {
	var raw map[string]interface{}
	if err := json.Unmarshal(value, &raw); err != nil {
		return err
	}
	if _, ok := raw["mainTarget"]; raw != nil && !ok {
		return fmt.Errorf("field mainTarget in ExpensesSchemaJsonOptimization: required")
	}
	if _, ok := raw["minimums"]; raw != nil && !ok {
		return fmt.Errorf("field minimums in ExpensesSchemaJsonOptimization: required")
	}
	type Plain ExpensesSchemaJsonOptimization
	var plain Plain
	if err := json.Unmarshal(value, &plain); err != nil {
		return err
	}
	if v, ok := raw["grossDividendMode"]; !ok || v == nil {
		plain.GrossDividendMode = "residual"
	}
	if v, ok := raw["mainTarget"]; !ok || v == nil {
		plain.MainTarget = "totalUsableIncome"
	}
	*j = ExpensesSchemaJsonOptimization(plain)
	return nil
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *ExpensesSchemaJson) UnmarshalJSON(value []byte) error {
	var raw map[string]interface{}
	if err := json.Unmarshal(value, &raw); err != nil {
		return err
	}
	if _, ok := raw["constraints"]; raw != nil && !ok {
		return fmt.Errorf("field constraints in ExpensesSchemaJson: required")
	}
	if _, ok := raw["currency"]; raw != nil && !ok {
		return fmt.Errorf("field currency in ExpensesSchemaJson: required")
	}
	if _, ok := raw["expenseGroups"]; raw != nil && !ok {
		return fmt.Errorf("field expenseGroups in ExpensesSchemaJson: required")
	}
	if _, ok := raw["optimization"]; raw != nil && !ok {
		return fmt.Errorf("field optimization in ExpensesSchemaJson: required")
	}
	if _, ok := raw["version"]; raw != nil && !ok {
		return fmt.Errorf("field version in ExpensesSchemaJson: required")
	}
	type Plain ExpensesSchemaJson
	var plain Plain
	if err := json.Unmarshal(value, &plain); err != nil {
		return err
	}
	if matched, _ := regexp.MatchString(`^[A-Z]{3}$`, string(plain.Currency)); !matched {
		return fmt.Errorf("field %s pattern match: must match %s", "Currency", `^[A-Z]{3}$`)
	}
	if utf8.RuneCountInString(string(plain.Version)) < 1 {
		return fmt.Errorf("field %s length: must be >= %d", "version", 1)
	}
	*j = ExpensesSchemaJson(plain)
	return nil
}

// Fixed monthly amount. Example: accounting fee, office rent, hosting subscription
// charged monthly.
type FixMonthCalculation struct {
	// Amount corresponds to the JSON schema field "amount".
	Amount NonNegativeMoneyAmount `json:"amount" yaml:"amount" mapstructure:"amount"`

	// Type corresponds to the JSON schema field "type".
	Type interface{} `json:"type" yaml:"type" mapstructure:"type"`
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *FixMonthCalculation) UnmarshalJSON(value []byte) error {
	var raw map[string]interface{}
	if err := json.Unmarshal(value, &raw); err != nil {
		return err
	}
	if _, ok := raw["amount"]; raw != nil && !ok {
		return fmt.Errorf("field amount in FixMonthCalculation: required")
	}
	if _, ok := raw["type"]; raw != nil && !ok {
		return fmt.Errorf("field type in FixMonthCalculation: required")
	}
	type Plain FixMonthCalculation
	var plain Plain
	if err := json.Unmarshal(value, &plain); err != nil {
		return err
	}
	*j = FixMonthCalculation(plain)
	return nil
}

// Fixed yearly amount. Example: annual hosting, annual chamber fee, yearly reserve
// amount. The application decides how to allocate this to month/year views.
type FixYearCalculation struct {
	// Amount corresponds to the JSON schema field "amount".
	Amount NonNegativeMoneyAmount `json:"amount" yaml:"amount" mapstructure:"amount"`

	// Type corresponds to the JSON schema field "type".
	Type interface{} `json:"type" yaml:"type" mapstructure:"type"`
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *FixYearCalculation) UnmarshalJSON(value []byte) error {
	var raw map[string]interface{}
	if err := json.Unmarshal(value, &raw); err != nil {
		return err
	}
	if _, ok := raw["amount"]; raw != nil && !ok {
		return fmt.Errorf("field amount in FixYearCalculation: required")
	}
	if _, ok := raw["type"]; raw != nil && !ok {
		return fmt.Errorf("field type in FixYearCalculation: required")
	}
	type Plain FixYearCalculation
	var plain Plain
	if err := json.Unmarshal(value, &plain); err != nil {
		return err
	}
	*j = FixYearCalculation(plain)
	return nil
}

type Frequency string

const FrequencyMonth Frequency = "month"
const FrequencyYear Frequency = "year"

var enumValues_Frequency = []interface{}{
	"month",
	"year",
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *Frequency) UnmarshalJSON(value []byte) error {
	var v string
	if err := json.Unmarshal(value, &v); err != nil {
		return err
	}
	var ok bool
	for _, expected := range enumValues_Frequency {
		if reflect.DeepEqual(v, expected) {
			ok = true
			break
		}
	}
	if !ok {
		return fmt.Errorf("invalid value (expected one of %#v): %#v", enumValues_Frequency, v)
	}
	*j = Frequency(v)
	return nil
}

type GrossDividendExpenseRow interface{}

type GrossDividendPercentAboveCapCalculation struct {
	// Basis corresponds to the JSON schema field "basis".
	Basis interface{} `json:"basis" yaml:"basis" mapstructure:"basis"`

	// CapAmount corresponds to the JSON schema field "capAmount".
	CapAmount NonNegativeMoneyAmount `json:"capAmount" yaml:"capAmount" mapstructure:"capAmount"`

	// Percent corresponds to the JSON schema field "percent".
	Percent Percentage `json:"percent" yaml:"percent" mapstructure:"percent"`

	// Type corresponds to the JSON schema field "type".
	Type interface{} `json:"type" yaml:"type" mapstructure:"type"`
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *GrossDividendPercentAboveCapCalculation) UnmarshalJSON(value []byte) error {
	var raw map[string]interface{}
	if err := json.Unmarshal(value, &raw); err != nil {
		return err
	}
	if _, ok := raw["basis"]; raw != nil && !ok {
		return fmt.Errorf("field basis in GrossDividendPercentAboveCapCalculation: required")
	}
	if _, ok := raw["capAmount"]; raw != nil && !ok {
		return fmt.Errorf("field capAmount in GrossDividendPercentAboveCapCalculation: required")
	}
	if _, ok := raw["percent"]; raw != nil && !ok {
		return fmt.Errorf("field percent in GrossDividendPercentAboveCapCalculation: required")
	}
	if _, ok := raw["type"]; raw != nil && !ok {
		return fmt.Errorf("field type in GrossDividendPercentAboveCapCalculation: required")
	}
	type Plain GrossDividendPercentAboveCapCalculation
	var plain Plain
	if err := json.Unmarshal(value, &plain); err != nil {
		return err
	}
	*j = GrossDividendPercentAboveCapCalculation(plain)
	return nil
}

type GrossDividendPercentBelowCapCalculation struct {
	// Basis corresponds to the JSON schema field "basis".
	Basis interface{} `json:"basis" yaml:"basis" mapstructure:"basis"`

	// CapAmount corresponds to the JSON schema field "capAmount".
	CapAmount NonNegativeMoneyAmount `json:"capAmount" yaml:"capAmount" mapstructure:"capAmount"`

	// Percent corresponds to the JSON schema field "percent".
	Percent Percentage `json:"percent" yaml:"percent" mapstructure:"percent"`

	// Type corresponds to the JSON schema field "type".
	Type interface{} `json:"type" yaml:"type" mapstructure:"type"`
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *GrossDividendPercentBelowCapCalculation) UnmarshalJSON(value []byte) error {
	var raw map[string]interface{}
	if err := json.Unmarshal(value, &raw); err != nil {
		return err
	}
	if _, ok := raw["basis"]; raw != nil && !ok {
		return fmt.Errorf("field basis in GrossDividendPercentBelowCapCalculation: required")
	}
	if _, ok := raw["capAmount"]; raw != nil && !ok {
		return fmt.Errorf("field capAmount in GrossDividendPercentBelowCapCalculation: required")
	}
	if _, ok := raw["percent"]; raw != nil && !ok {
		return fmt.Errorf("field percent in GrossDividendPercentBelowCapCalculation: required")
	}
	if _, ok := raw["type"]; raw != nil && !ok {
		return fmt.Errorf("field type in GrossDividendPercentBelowCapCalculation: required")
	}
	type Plain GrossDividendPercentBelowCapCalculation
	var plain Plain
	if err := json.Unmarshal(value, &plain); err != nil {
		return err
	}
	*j = GrossDividendPercentBelowCapCalculation(plain)
	return nil
}

type GrossDividendPercentCalculation struct {
	// Basis corresponds to the JSON schema field "basis".
	Basis interface{} `json:"basis" yaml:"basis" mapstructure:"basis"`

	// Percent corresponds to the JSON schema field "percent".
	Percent Percentage `json:"percent" yaml:"percent" mapstructure:"percent"`

	// Type corresponds to the JSON schema field "type".
	Type interface{} `json:"type" yaml:"type" mapstructure:"type"`
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *GrossDividendPercentCalculation) UnmarshalJSON(value []byte) error {
	var raw map[string]interface{}
	if err := json.Unmarshal(value, &raw); err != nil {
		return err
	}
	if _, ok := raw["basis"]; raw != nil && !ok {
		return fmt.Errorf("field basis in GrossDividendPercentCalculation: required")
	}
	if _, ok := raw["percent"]; raw != nil && !ok {
		return fmt.Errorf("field percent in GrossDividendPercentCalculation: required")
	}
	if _, ok := raw["type"]; raw != nil && !ok {
		return fmt.Errorf("field type in GrossDividendPercentCalculation: required")
	}
	type Plain GrossDividendPercentCalculation
	var plain Plain
	if err := json.Unmarshal(value, &plain); err != nil {
		return err
	}
	*j = GrossDividendPercentCalculation(plain)
	return nil
}

type GrossSalaryExpenseRow interface{}

type GrossSalaryPercentAboveCapCalculation struct {
	// Basis corresponds to the JSON schema field "basis".
	Basis interface{} `json:"basis" yaml:"basis" mapstructure:"basis"`

	// CapAmount corresponds to the JSON schema field "capAmount".
	CapAmount NonNegativeMoneyAmount `json:"capAmount" yaml:"capAmount" mapstructure:"capAmount"`

	// Percent corresponds to the JSON schema field "percent".
	Percent Percentage `json:"percent" yaml:"percent" mapstructure:"percent"`

	// Type corresponds to the JSON schema field "type".
	Type interface{} `json:"type" yaml:"type" mapstructure:"type"`
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *GrossSalaryPercentAboveCapCalculation) UnmarshalJSON(value []byte) error {
	var raw map[string]interface{}
	if err := json.Unmarshal(value, &raw); err != nil {
		return err
	}
	if _, ok := raw["basis"]; raw != nil && !ok {
		return fmt.Errorf("field basis in GrossSalaryPercentAboveCapCalculation: required")
	}
	if _, ok := raw["capAmount"]; raw != nil && !ok {
		return fmt.Errorf("field capAmount in GrossSalaryPercentAboveCapCalculation: required")
	}
	if _, ok := raw["percent"]; raw != nil && !ok {
		return fmt.Errorf("field percent in GrossSalaryPercentAboveCapCalculation: required")
	}
	if _, ok := raw["type"]; raw != nil && !ok {
		return fmt.Errorf("field type in GrossSalaryPercentAboveCapCalculation: required")
	}
	type Plain GrossSalaryPercentAboveCapCalculation
	var plain Plain
	if err := json.Unmarshal(value, &plain); err != nil {
		return err
	}
	*j = GrossSalaryPercentAboveCapCalculation(plain)
	return nil
}

type GrossSalaryPercentBelowCapCalculation struct {
	// Basis corresponds to the JSON schema field "basis".
	Basis interface{} `json:"basis" yaml:"basis" mapstructure:"basis"`

	// CapAmount corresponds to the JSON schema field "capAmount".
	CapAmount NonNegativeMoneyAmount `json:"capAmount" yaml:"capAmount" mapstructure:"capAmount"`

	// Percent corresponds to the JSON schema field "percent".
	Percent Percentage `json:"percent" yaml:"percent" mapstructure:"percent"`

	// Type corresponds to the JSON schema field "type".
	Type interface{} `json:"type" yaml:"type" mapstructure:"type"`
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *GrossSalaryPercentBelowCapCalculation) UnmarshalJSON(value []byte) error {
	var raw map[string]interface{}
	if err := json.Unmarshal(value, &raw); err != nil {
		return err
	}
	if _, ok := raw["basis"]; raw != nil && !ok {
		return fmt.Errorf("field basis in GrossSalaryPercentBelowCapCalculation: required")
	}
	if _, ok := raw["capAmount"]; raw != nil && !ok {
		return fmt.Errorf("field capAmount in GrossSalaryPercentBelowCapCalculation: required")
	}
	if _, ok := raw["percent"]; raw != nil && !ok {
		return fmt.Errorf("field percent in GrossSalaryPercentBelowCapCalculation: required")
	}
	if _, ok := raw["type"]; raw != nil && !ok {
		return fmt.Errorf("field type in GrossSalaryPercentBelowCapCalculation: required")
	}
	type Plain GrossSalaryPercentBelowCapCalculation
	var plain Plain
	if err := json.Unmarshal(value, &plain); err != nil {
		return err
	}
	*j = GrossSalaryPercentBelowCapCalculation(plain)
	return nil
}

type GrossSalaryPercentCalculation struct {
	// Basis corresponds to the JSON schema field "basis".
	Basis interface{} `json:"basis" yaml:"basis" mapstructure:"basis"`

	// Percent corresponds to the JSON schema field "percent".
	Percent Percentage `json:"percent" yaml:"percent" mapstructure:"percent"`

	// Type corresponds to the JSON schema field "type".
	Type interface{} `json:"type" yaml:"type" mapstructure:"type"`
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *GrossSalaryPercentCalculation) UnmarshalJSON(value []byte) error {
	var raw map[string]interface{}
	if err := json.Unmarshal(value, &raw); err != nil {
		return err
	}
	if _, ok := raw["basis"]; raw != nil && !ok {
		return fmt.Errorf("field basis in GrossSalaryPercentCalculation: required")
	}
	if _, ok := raw["percent"]; raw != nil && !ok {
		return fmt.Errorf("field percent in GrossSalaryPercentCalculation: required")
	}
	if _, ok := raw["type"]; raw != nil && !ok {
		return fmt.Errorf("field type in GrossSalaryPercentCalculation: required")
	}
	type Plain GrossSalaryPercentCalculation
	var plain Plain
	if err := json.Unmarshal(value, &plain); err != nil {
		return err
	}
	*j = GrossSalaryPercentCalculation(plain)
	return nil
}

// A lower-bound rule. 'disabled' means no minimum. 'fixed' means a non-negative
// fixed amount. 'percentOfCompanyIncome' means a percentage of company income.
// This is intended for constraints and optimization minimums, not for ordinary
// expense rows.
type MinimumRule interface{}

type MinimumRuleMode string

const MinimumRuleModeDisabled MinimumRuleMode = "disabled"
const MinimumRuleModeFixed MinimumRuleMode = "fixed"
const MinimumRuleModePercentOfCompanyIncome MinimumRuleMode = "percentOfCompanyIncome"

var enumValues_MinimumRuleMode = []interface{}{
	"disabled",
	"fixed",
	"percentOfCompanyIncome",
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *MinimumRuleMode) UnmarshalJSON(value []byte) error {
	var v string
	if err := json.Unmarshal(value, &v); err != nil {
		return err
	}
	var ok bool
	for _, expected := range enumValues_MinimumRuleMode {
		if reflect.DeepEqual(v, expected) {
			ok = true
			break
		}
	}
	if !ok {
		return fmt.Errorf("invalid value (expected one of %#v): %#v", enumValues_MinimumRuleMode, v)
	}
	*j = MinimumRuleMode(v)
	return nil
}

// Human-readable row name. Names are free-form so country-specific rows can be
// modeled without code changes.
type NonEmptyName string

// UnmarshalJSON implements json.Unmarshaler.
func (j *NonEmptyName) UnmarshalJSON(value []byte) error {
	type Plain NonEmptyName
	var plain Plain
	if err := json.Unmarshal(value, &plain); err != nil {
		return err
	}
	if utf8.RuneCountInString(string(plain)) < 1 {
		return fmt.Errorf("field %s length: must be >= %d", "", 1)
	}
	if utf8.RuneCountInString(string(plain)) > 120 {
		return fmt.Errorf("field %s length: must be <= %d", "", 120)
	}
	*j = NonEmptyName(plain)
	return nil
}

// A non-negative money amount in the configuration currency.
type NonNegativeMoneyAmount float64

// UnmarshalJSON implements json.Unmarshaler.
func (j *NonNegativeMoneyAmount) UnmarshalJSON(value []byte) error {
	type Plain NonNegativeMoneyAmount
	var plain Plain
	if err := json.Unmarshal(value, &plain); err != nil {
		return err
	}
	if 0 > plain {
		return fmt.Errorf("field %s: must be >= %v", "", 0)
	}
	*j = NonNegativeMoneyAmount(plain)
	return nil
}

// Percentage applied only to the part of the basis above the cap. Example: 10% of
// salary above a social-contribution cap. If the basis is 5,000 and the cap is
// 2,000, this row applies to 3,000.
type PercentAboveCapCalculation struct {
	// Basis corresponds to the JSON schema field "basis".
	Basis Basis `json:"basis" yaml:"basis" mapstructure:"basis"`

	// CapAmount corresponds to the JSON schema field "capAmount".
	CapAmount NonNegativeMoneyAmount `json:"capAmount" yaml:"capAmount" mapstructure:"capAmount"`

	// Percent corresponds to the JSON schema field "percent".
	Percent Percentage `json:"percent" yaml:"percent" mapstructure:"percent"`

	// Type corresponds to the JSON schema field "type".
	Type interface{} `json:"type" yaml:"type" mapstructure:"type"`
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *PercentAboveCapCalculation) UnmarshalJSON(value []byte) error {
	var raw map[string]interface{}
	if err := json.Unmarshal(value, &raw); err != nil {
		return err
	}
	if _, ok := raw["basis"]; raw != nil && !ok {
		return fmt.Errorf("field basis in PercentAboveCapCalculation: required")
	}
	if _, ok := raw["capAmount"]; raw != nil && !ok {
		return fmt.Errorf("field capAmount in PercentAboveCapCalculation: required")
	}
	if _, ok := raw["percent"]; raw != nil && !ok {
		return fmt.Errorf("field percent in PercentAboveCapCalculation: required")
	}
	if _, ok := raw["type"]; raw != nil && !ok {
		return fmt.Errorf("field type in PercentAboveCapCalculation: required")
	}
	type Plain PercentAboveCapCalculation
	var plain Plain
	if err := json.Unmarshal(value, &plain); err != nil {
		return err
	}
	*j = PercentAboveCapCalculation(plain)
	return nil
}

// Percentage applied only to the part of the basis up to the cap. Example: 20% of
// salary below a social-contribution cap. If the basis is 5,000 and the cap is
// 2,000, this row applies to 2,000.
type PercentBelowCapCalculation struct {
	// Basis corresponds to the JSON schema field "basis".
	Basis Basis `json:"basis" yaml:"basis" mapstructure:"basis"`

	// CapAmount corresponds to the JSON schema field "capAmount".
	CapAmount NonNegativeMoneyAmount `json:"capAmount" yaml:"capAmount" mapstructure:"capAmount"`

	// Percent corresponds to the JSON schema field "percent".
	Percent Percentage `json:"percent" yaml:"percent" mapstructure:"percent"`

	// Type corresponds to the JSON schema field "type".
	Type interface{} `json:"type" yaml:"type" mapstructure:"type"`
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *PercentBelowCapCalculation) UnmarshalJSON(value []byte) error {
	var raw map[string]interface{}
	if err := json.Unmarshal(value, &raw); err != nil {
		return err
	}
	if _, ok := raw["basis"]; raw != nil && !ok {
		return fmt.Errorf("field basis in PercentBelowCapCalculation: required")
	}
	if _, ok := raw["capAmount"]; raw != nil && !ok {
		return fmt.Errorf("field capAmount in PercentBelowCapCalculation: required")
	}
	if _, ok := raw["percent"]; raw != nil && !ok {
		return fmt.Errorf("field percent in PercentBelowCapCalculation: required")
	}
	if _, ok := raw["type"]; raw != nil && !ok {
		return fmt.Errorf("field type in PercentBelowCapCalculation: required")
	}
	type Plain PercentBelowCapCalculation
	var plain Plain
	if err := json.Unmarshal(value, &plain); err != nil {
		return err
	}
	*j = PercentBelowCapCalculation(plain)
	return nil
}

// Simple percentage of a basis. Example: 10% of company profit for corporate tax,
// 5% of gross dividend for dividend tax, or 10% of company income for a company
// reserve.
type PercentCalculation struct {
	// Basis corresponds to the JSON schema field "basis".
	Basis Basis `json:"basis" yaml:"basis" mapstructure:"basis"`

	// Percent corresponds to the JSON schema field "percent".
	Percent Percentage `json:"percent" yaml:"percent" mapstructure:"percent"`

	// Type corresponds to the JSON schema field "type".
	Type interface{} `json:"type" yaml:"type" mapstructure:"type"`
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *PercentCalculation) UnmarshalJSON(value []byte) error {
	var raw map[string]interface{}
	if err := json.Unmarshal(value, &raw); err != nil {
		return err
	}
	if _, ok := raw["basis"]; raw != nil && !ok {
		return fmt.Errorf("field basis in PercentCalculation: required")
	}
	if _, ok := raw["percent"]; raw != nil && !ok {
		return fmt.Errorf("field percent in PercentCalculation: required")
	}
	if _, ok := raw["type"]; raw != nil && !ok {
		return fmt.Errorf("field type in PercentCalculation: required")
	}
	type Plain PercentCalculation
	var plain Plain
	if err := json.Unmarshal(value, &plain); err != nil {
		return err
	}
	*j = PercentCalculation(plain)
	return nil
}

// Percentage value between 0 and 100. Use 10 for 10%, not 0.10.
type Percentage float64

// UnmarshalJSON implements json.Unmarshaler.
func (j *Percentage) UnmarshalJSON(value []byte) error {
	type Plain Percentage
	var plain Plain
	if err := json.Unmarshal(value, &plain); err != nil {
		return err
	}
	if 100 < plain {
		return fmt.Errorf("field %s: must be <= %v", "", 100)
	}
	if 0 > plain {
		return fmt.Errorf("field %s: must be >= %v", "", 0)
	}
	*j = Percentage(plain)
	return nil
}

// A positive money amount in the configuration currency.
type PositiveMoneyAmount float64

// UnmarshalJSON implements json.Unmarshaler.
func (j *PositiveMoneyAmount) UnmarshalJSON(value []byte) error {
	type Plain PositiveMoneyAmount
	var plain Plain
	if err := json.Unmarshal(value, &plain); err != nil {
		return err
	}
	if 0 >= plain {
		return fmt.Errorf("field %s: must be > %v", "", 0)
	}
	*j = PositiveMoneyAmount(plain)
	return nil
}

type RowBaseCommon struct {
	// The calculation used for this row. Exactly one shape is selected by the 'type'
	// field. Fixed rows require an amount and a frequency. Percentage rows require a
	// basis and a rate. Below-cap and above-cap percentage rows additionally require
	// a cap amount.
	Calculation RowBaseCommonCalculation `json:"calculation" yaml:"calculation" mapstructure:"calculation"`

	// Optional documentation for humans and AI agents. Use this to explain legal
	// assumptions, simplifications, or why the row exists.
	Description *string `json:"description,omitempty,omitzero" yaml:"description,omitempty" mapstructure:"description,omitempty"`

	// Whether this row is active. Omitted means true.
	Enabled bool `json:"enabled,omitempty,omitzero" yaml:"enabled,omitempty" mapstructure:"enabled,omitempty"`

	// Name corresponds to the JSON schema field "name".
	Name NonEmptyName `json:"name" yaml:"name" mapstructure:"name"`
}

// The calculation used for this row. Exactly one shape is selected by the 'type'
// field. Fixed rows require an amount and a frequency. Percentage rows require a
// basis and a rate. Below-cap and above-cap percentage rows additionally require a
// cap amount.
type RowBaseCommonCalculation map[string]interface{}

// UnmarshalJSON implements json.Unmarshaler.
func (j *RowBaseCommon) UnmarshalJSON(value []byte) error {
	var raw map[string]interface{}
	if err := json.Unmarshal(value, &raw); err != nil {
		return err
	}
	if _, ok := raw["calculation"]; raw != nil && !ok {
		return fmt.Errorf("field calculation in RowBaseCommon: required")
	}
	if _, ok := raw["name"]; raw != nil && !ok {
		return fmt.Errorf("field name in RowBaseCommon: required")
	}
	type Plain RowBaseCommon
	var plain Plain
	if err := json.Unmarshal(value, &plain); err != nil {
		return err
	}
	if plain.Description != nil && utf8.RuneCountInString(string(*plain.Description)) > 2000 {
		return fmt.Errorf("field %s length: must be <= %d", "description", 2000)
	}
	if v, ok := raw["enabled"]; !ok || v == nil {
		plain.Enabled = true
	}
	*j = RowBaseCommon(plain)
	return nil
}

// The gross salary row itself. This is a pass-through row whose amount is the
// configured or optimized gross salary. It is mainly used in company-side expense
// groups because gross salary reduces company profit. It should normally not be
// used inside grossSalaryExpenses, where only deductions from gross salary belong.
type SalaryCalculation struct {
	// Type corresponds to the JSON schema field "type".
	Type interface{} `json:"type" yaml:"type" mapstructure:"type"`
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *SalaryCalculation) UnmarshalJSON(value []byte) error {
	var raw map[string]interface{}
	if err := json.Unmarshal(value, &raw); err != nil {
		return err
	}
	if _, ok := raw["type"]; raw != nil && !ok {
		return fmt.Errorf("field type in SalaryCalculation: required")
	}
	type Plain SalaryCalculation
	var plain Plain
	if err := json.Unmarshal(value, &plain); err != nil {
		return err
	}
	*j = SalaryCalculation(plain)
	return nil
}

type SettingsSchemaJson struct {
	// AppName corresponds to the JSON schema field "appName".
	AppName string `json:"appName" yaml:"appName" mapstructure:"appName"`
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *SettingsSchemaJson) UnmarshalJSON(value []byte) error {
	var raw map[string]interface{}
	if err := json.Unmarshal(value, &raw); err != nil {
		return err
	}
	if _, ok := raw["appName"]; raw != nil && !ok {
		return fmt.Errorf("field appName in SettingsSchemaJson: required")
	}
	type Plain SettingsSchemaJson
	var plain Plain
	if err := json.Unmarshal(value, &plain); err != nil {
		return err
	}
	if utf8.RuneCountInString(string(plain.AppName)) < 1 {
		return fmt.Errorf("field %s length: must be >= %d", "appName", 1)
	}
	*j = SettingsSchemaJson(plain)
	return nil
}
