// Code generated by github.com/atombender/go-jsonschema, DO NOT EDIT.

package main

import "encoding/json"
import "fmt"
import "unicode/utf8"

type ExpensesSchemaJson struct {
	// Title corresponds to the JSON schema field "title".
	Title string `json:"title" yaml:"title" mapstructure:"title"`
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *ExpensesSchemaJson) UnmarshalJSON(value []byte) error {
	var raw map[string]interface{}
	if err := json.Unmarshal(value, &raw); err != nil {
		return err
	}
	if _, ok := raw["title"]; raw != nil && !ok {
		return fmt.Errorf("field title in ExpensesSchemaJson: required")
	}
	type Plain ExpensesSchemaJson
	var plain Plain
	if err := json.Unmarshal(value, &plain); err != nil {
		return err
	}
	if utf8.RuneCountInString(string(plain.Title)) < 1 {
		return fmt.Errorf("field %s length: must be >= %d", "title", 1)
	}
	*j = ExpensesSchemaJson(plain)
	return nil
}

type SettingsSchemaJson struct {
	// AppName corresponds to the JSON schema field "appName".
	AppName string `json:"appName" yaml:"appName" mapstructure:"appName"`
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *SettingsSchemaJson) UnmarshalJSON(value []byte) error {
	var raw map[string]interface{}
	if err := json.Unmarshal(value, &raw); err != nil {
		return err
	}
	if _, ok := raw["appName"]; raw != nil && !ok {
		return fmt.Errorf("field appName in SettingsSchemaJson: required")
	}
	type Plain SettingsSchemaJson
	var plain Plain
	if err := json.Unmarshal(value, &plain); err != nil {
		return err
	}
	if utf8.RuneCountInString(string(plain.AppName)) < 1 {
		return fmt.Errorf("field %s length: must be >= %d", "appName", 1)
	}
	*j = SettingsSchemaJson(plain)
	return nil
}
