name: Release

on:
  push:
    tags:
      - '*'

permissions:
  contents: write

jobs:
  release:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        include:
          - os: ubuntu-latest
            GOOS: linux
            GOARCH: amd64
            EXT: ""
          - os: macos-latest
            GOOS: darwin
            GOARCH: amd64
            EXT: ""
          - os: windows-latest
            GOOS: windows
            GOARCH: amd64
            EXT: ".exe"
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Go
        uses: actions/setup-go@v6
        with:
          go-version: '1.26'
      
      - name: Install generate tool
        run: make install-generate
      
      - name: Generate schema code
        run: make generate
      
      - name: Build binary
        env:
          GOOS: ${{ matrix.GOOS }}
          GOARCH: ${{ matrix.GOARCH }}
        run: |
          go build -ldflags="-s -w" -o "bin/income-atlas-${{ matrix.GOOS }}-${{ matrix.GOARCH }}${{ matrix.EXT }}" .

      - name: Upload release asset
        uses: softprops/action-gh-release@v2
        with:
          files: bin/income-atlas-${{ matrix.GOOS }}-${{ matrix.GOARCH }}${{ matrix.EXT }}
          draft: false
